#[cfg(feature = "nota-text")]
mod render_tests {
    use std::fs;

    use spirit::{
        render::{
            RenderDirectory, RenderError, RenderInputSource, RenderReferent, RenderReferents,
            RenderRequest, RenderTimestamp, RenderedIntent,
        },
        schema::signal::{
            CommitSequence, DatabaseMarker, ObservedRecords, Output, RecordSet, StateDigest,
        },
    };
    use tempfile::TempDir;

    #[test]
    fn render_request_is_a_single_nota_record_with_optional_directory() {
        let source = RenderInputSource::new(String::from("(Render ([spirit criome] None))"));
        let request = source.parse_request().expect("render request should parse");

        let output_path = request.output_path().expect("default output path");
        assert_eq!(
            output_path.file_name().and_then(|name| name.to_str()),
            Some("spirit.nota")
        );
    }

    #[test]
    fn render_request_rejects_empty_referents() {
        let source = RenderInputSource::new(String::from("(Render ([] None))"));
        let error = source
            .parse_request()
            .expect_err("empty referent set should be rejected");

        assert!(matches!(error, RenderError::EmptyReferents));
    }

    #[test]
    fn rendered_intent_writes_spirit_nota_in_requested_directory() {
        let temp = TempDir::new().expect("tempdir");
        let output_directory = temp.path().join("repo");
        let request = RenderRequest::new(
            RenderReferents::new(vec![RenderReferent::new("spirit")]),
            Some(RenderDirectory::new(output_directory.display().to_string())),
        );
        let marker = Output::marker_reported(DatabaseMarker {
            commit_sequence: CommitSequence::new(7),
            state_digest: StateDigest::new(11),
        });
        let records = Output::records_observed(ObservedRecords::new(RecordSet::new(Vec::new())));
        let rendered = RenderedIntent::new(request, marker, records, RenderTimestamp::new(42));

        let output_path = rendered.write().expect("rendered output");
        assert_eq!(output_path, output_directory.join("spirit.nota"));

        let document = fs::read_to_string(output_path).expect("rendered file");
        assert!(document.contains(";; @generated by spirit-render"));
        assert!(document.contains(";; generated-unix-timestamp-seconds: 42"));
        assert!(document.contains(";; privacy-filter: Zero"));
        assert!(document.contains(";; criome-auth-reference: None"));
        assert!(document.contains("(MarkerReported (7 11))"));
        assert!(document.trim_end().ends_with("(RecordsObserved [])"));
    }
}
