// @generated by schema-rust-next

pub type String = std::string::String;
pub type Integer = u64;
pub type Boolean = bool;
pub type Path = std::string::String;

pub use nota_next::{
    NotaBlock, NotaDecode, NotaDecodeError, NotaEncode, NotaSource,
};

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SourcePath(pub String);

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct LocalPath(pub String);

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PublicPath(pub String);

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Import {
    pub source_path: SourcePath,
    pub local_path: LocalPath,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Export {
    pub local_path: LocalPath,
    pub public_path: PublicPath,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SignalReuse {
    pub import: Import,
    pub export: Export,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct NexusReuse {
    pub import: Import,
    pub export: Export,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SemaReuse {
    pub import: Import,
    pub export: Export,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusInput {
    Signal(Input),
    Sema(SemaOutput),
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusOutput {
    Sema(SemaInput),
    Signal(Output),
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SemaInput {
    Record(Entry),
    Observe(Query),
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SemaOutput {
    Recorded(SemaReceipt),
    Observed(ObservedRecords),
    Missed(ErrorReport),
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Topic(pub String);

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Description(pub String);

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ErrorMessage(pub String);

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RecordIdentifier(pub Integer);

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CommitSequence(pub Integer);

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StateDigest(pub Integer);

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DatabaseMarker {
    pub commit_sequence: CommitSequence,
    pub state_digest: StateDigest,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SemaReceipt {
    pub record_identifier: RecordIdentifier,
    pub database_marker: DatabaseMarker,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ObservedRecords {
    pub record_set: RecordSet,
    pub database_marker: DatabaseMarker,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ErrorReport {
    pub error_message: ErrorMessage,
    pub database_marker: DatabaseMarker,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SignalRejection {
    pub validation_error: ValidationError,
    pub database_marker: DatabaseMarker,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ValidationError {
    EmptyTopic,
    EmptyDescription,
    EmptyQueryTopic,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MailIdentifier(pub Integer);

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ShortHeader(pub Integer);

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SentMail {
    pub mail_identifier: MailIdentifier,
    pub origin_route: OriginRoute,
    pub short_header: ShortHeader,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ProcessedMail {
    pub mail_identifier: MailIdentifier,
    pub origin_route: OriginRoute,
    pub database_marker: DatabaseMarker,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum MailLedgerEvent {
    Sent(SentMail),
    Processed(ProcessedMail),
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Entry {
    pub topic: Topic,
    pub kind: Kind,
    pub description: Description,
    pub magnitude: Magnitude,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Query {
    pub topic: Topic,
    pub kind: Kind,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RecordSet(pub Entry);

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Kind {
    Decision,
    Principle,
    Correction,
    Clarification,
    Constraint,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Magnitude {
    Minimum,
    VeryLow,
    Low,
    Medium,
    High,
    VeryHigh,
    Maximum,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    Record(Entry),
    Observe(Query),
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    RecordAccepted(SemaReceipt),
    RecordsObserved(ObservedRecords),
    Error(ErrorReport),
    Rejected(SignalRejection),
}

impl NotaDecode for SourcePath {
    fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        Ok(Self(<String as NotaDecode>::from_nota_block(block)?))
    }
}

impl NotaEncode for SourcePath {
    fn to_nota(&self) -> String {
        NotaEncode::to_nota(&self.0)
    }
}

impl SourcePath {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

impl NotaDecode for LocalPath {
    fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        Ok(Self(<String as NotaDecode>::from_nota_block(block)?))
    }
}

impl NotaEncode for LocalPath {
    fn to_nota(&self) -> String {
        NotaEncode::to_nota(&self.0)
    }
}

impl LocalPath {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

impl NotaDecode for PublicPath {
    fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        Ok(Self(<String as NotaDecode>::from_nota_block(block)?))
    }
}

impl NotaEncode for PublicPath {
    fn to_nota(&self) -> String {
        NotaEncode::to_nota(&self.0)
    }
}

impl PublicPath {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

impl NotaDecode for Import {
    fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        let children = NotaBlock::new(block).expect_children(nota_next::Delimiter::Parenthesis, "parenthesis", "Import", 2)?;
        Ok(Self {
            source_path: <SourcePath as NotaDecode>::from_nota_block(&children[0])?,
            local_path: <LocalPath as NotaDecode>::from_nota_block(&children[1])?,
        })
    }
}

impl NotaEncode for Import {
    fn to_nota(&self) -> String {
        let fields = [
            NotaEncode::to_nota(&self.source_path),
            NotaEncode::to_nota(&self.local_path),
        ];
        format!("({})", fields.join(" "))
    }
}

impl Import {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

impl NotaDecode for Export {
    fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        let children = NotaBlock::new(block).expect_children(nota_next::Delimiter::Parenthesis, "parenthesis", "Export", 2)?;
        Ok(Self {
            local_path: <LocalPath as NotaDecode>::from_nota_block(&children[0])?,
            public_path: <PublicPath as NotaDecode>::from_nota_block(&children[1])?,
        })
    }
}

impl NotaEncode for Export {
    fn to_nota(&self) -> String {
        let fields = [
            NotaEncode::to_nota(&self.local_path),
            NotaEncode::to_nota(&self.public_path),
        ];
        format!("({})", fields.join(" "))
    }
}

impl Export {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

impl NotaDecode for SignalReuse {
    fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        let children = NotaBlock::new(block).expect_children(nota_next::Delimiter::Parenthesis, "parenthesis", "SignalReuse", 2)?;
        Ok(Self {
            import: <Import as NotaDecode>::from_nota_block(&children[0])?,
            export: <Export as NotaDecode>::from_nota_block(&children[1])?,
        })
    }
}

impl NotaEncode for SignalReuse {
    fn to_nota(&self) -> String {
        let fields = [
            NotaEncode::to_nota(&self.import),
            NotaEncode::to_nota(&self.export),
        ];
        format!("({})", fields.join(" "))
    }
}

impl SignalReuse {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

impl NotaDecode for NexusReuse {
    fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        let children = NotaBlock::new(block).expect_children(nota_next::Delimiter::Parenthesis, "parenthesis", "NexusReuse", 2)?;
        Ok(Self {
            import: <Import as NotaDecode>::from_nota_block(&children[0])?,
            export: <Export as NotaDecode>::from_nota_block(&children[1])?,
        })
    }
}

impl NotaEncode for NexusReuse {
    fn to_nota(&self) -> String {
        let fields = [
            NotaEncode::to_nota(&self.import),
            NotaEncode::to_nota(&self.export),
        ];
        format!("({})", fields.join(" "))
    }
}

impl NexusReuse {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

impl NotaDecode for SemaReuse {
    fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        let children = NotaBlock::new(block).expect_children(nota_next::Delimiter::Parenthesis, "parenthesis", "SemaReuse", 2)?;
        Ok(Self {
            import: <Import as NotaDecode>::from_nota_block(&children[0])?,
            export: <Export as NotaDecode>::from_nota_block(&children[1])?,
        })
    }
}

impl NotaEncode for SemaReuse {
    fn to_nota(&self) -> String {
        let fields = [
            NotaEncode::to_nota(&self.import),
            NotaEncode::to_nota(&self.export),
        ];
        format!("({})", fields.join(" "))
    }
}

impl SemaReuse {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

impl NotaDecode for NexusInput {
    fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        if let Some(variant) = block.demote_to_string() {
            return Err(NotaDecodeError::UnknownVariant { enum_name: "NexusInput", variant: variant.to_owned() });
        }
        let children = NotaBlock::new(block).expect_children(nota_next::Delimiter::Parenthesis, "parenthesis", "NexusInput", 2)?;
        let variant = children[0].demote_to_string().ok_or(NotaDecodeError::ExpectedAtom { type_name: "enum variant" })?;
        match variant {
            "Signal" => Ok(Self::Signal(<Input as NotaDecode>::from_nota_block(&children[1])?)),
            "Sema" => Ok(Self::Sema(<SemaOutput as NotaDecode>::from_nota_block(&children[1])?)),
            other => Err(NotaDecodeError::UnknownVariant { enum_name: "NexusInput", variant: other.to_owned() }),
        }
    }

}

impl NotaEncode for NexusInput {
    fn to_nota(&self) -> String {
        match self {
            Self::Signal(payload) => format!("(Signal {})", NotaEncode::to_nota(payload)),
            Self::Sema(payload) => format!("(Sema {})", NotaEncode::to_nota(payload)),
        }
    }
}

impl NexusInput {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

impl NotaDecode for NexusOutput {
    fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        if let Some(variant) = block.demote_to_string() {
            return Err(NotaDecodeError::UnknownVariant { enum_name: "NexusOutput", variant: variant.to_owned() });
        }
        let children = NotaBlock::new(block).expect_children(nota_next::Delimiter::Parenthesis, "parenthesis", "NexusOutput", 2)?;
        let variant = children[0].demote_to_string().ok_or(NotaDecodeError::ExpectedAtom { type_name: "enum variant" })?;
        match variant {
            "Sema" => Ok(Self::Sema(<SemaInput as NotaDecode>::from_nota_block(&children[1])?)),
            "Signal" => Ok(Self::Signal(<Output as NotaDecode>::from_nota_block(&children[1])?)),
            other => Err(NotaDecodeError::UnknownVariant { enum_name: "NexusOutput", variant: other.to_owned() }),
        }
    }

}

impl NotaEncode for NexusOutput {
    fn to_nota(&self) -> String {
        match self {
            Self::Sema(payload) => format!("(Sema {})", NotaEncode::to_nota(payload)),
            Self::Signal(payload) => format!("(Signal {})", NotaEncode::to_nota(payload)),
        }
    }
}

impl NexusOutput {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

impl NotaDecode for SemaInput {
    fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        if let Some(variant) = block.demote_to_string() {
            return Err(NotaDecodeError::UnknownVariant { enum_name: "SemaInput", variant: variant.to_owned() });
        }
        let children = NotaBlock::new(block).expect_children(nota_next::Delimiter::Parenthesis, "parenthesis", "SemaInput", 2)?;
        let variant = children[0].demote_to_string().ok_or(NotaDecodeError::ExpectedAtom { type_name: "enum variant" })?;
        match variant {
            "Record" => Ok(Self::Record(<Entry as NotaDecode>::from_nota_block(&children[1])?)),
            "Observe" => Ok(Self::Observe(<Query as NotaDecode>::from_nota_block(&children[1])?)),
            other => Err(NotaDecodeError::UnknownVariant { enum_name: "SemaInput", variant: other.to_owned() }),
        }
    }

}

impl NotaEncode for SemaInput {
    fn to_nota(&self) -> String {
        match self {
            Self::Record(payload) => format!("(Record {})", NotaEncode::to_nota(payload)),
            Self::Observe(payload) => format!("(Observe {})", NotaEncode::to_nota(payload)),
        }
    }
}

impl SemaInput {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

impl NotaDecode for SemaOutput {
    fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        if let Some(variant) = block.demote_to_string() {
            return Err(NotaDecodeError::UnknownVariant { enum_name: "SemaOutput", variant: variant.to_owned() });
        }
        let children = NotaBlock::new(block).expect_children(nota_next::Delimiter::Parenthesis, "parenthesis", "SemaOutput", 2)?;
        let variant = children[0].demote_to_string().ok_or(NotaDecodeError::ExpectedAtom { type_name: "enum variant" })?;
        match variant {
            "Recorded" => Ok(Self::Recorded(<SemaReceipt as NotaDecode>::from_nota_block(&children[1])?)),
            "Observed" => Ok(Self::Observed(<ObservedRecords as NotaDecode>::from_nota_block(&children[1])?)),
            "Missed" => Ok(Self::Missed(<ErrorReport as NotaDecode>::from_nota_block(&children[1])?)),
            other => Err(NotaDecodeError::UnknownVariant { enum_name: "SemaOutput", variant: other.to_owned() }),
        }
    }

}

impl NotaEncode for SemaOutput {
    fn to_nota(&self) -> String {
        match self {
            Self::Recorded(payload) => format!("(Recorded {})", NotaEncode::to_nota(payload)),
            Self::Observed(payload) => format!("(Observed {})", NotaEncode::to_nota(payload)),
            Self::Missed(payload) => format!("(Missed {})", NotaEncode::to_nota(payload)),
        }
    }
}

impl SemaOutput {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

impl NotaDecode for Topic {
    fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        Ok(Self(<String as NotaDecode>::from_nota_block(block)?))
    }
}

impl NotaEncode for Topic {
    fn to_nota(&self) -> String {
        NotaEncode::to_nota(&self.0)
    }
}

impl Topic {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

impl NotaDecode for Description {
    fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        Ok(Self(<String as NotaDecode>::from_nota_block(block)?))
    }
}

impl NotaEncode for Description {
    fn to_nota(&self) -> String {
        NotaEncode::to_nota(&self.0)
    }
}

impl Description {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

impl NotaDecode for ErrorMessage {
    fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        Ok(Self(<String as NotaDecode>::from_nota_block(block)?))
    }
}

impl NotaEncode for ErrorMessage {
    fn to_nota(&self) -> String {
        NotaEncode::to_nota(&self.0)
    }
}

impl ErrorMessage {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

impl NotaDecode for RecordIdentifier {
    fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        Ok(Self(<Integer as NotaDecode>::from_nota_block(block)?))
    }
}

impl NotaEncode for RecordIdentifier {
    fn to_nota(&self) -> String {
        NotaEncode::to_nota(&self.0)
    }
}

impl RecordIdentifier {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

impl NotaDecode for CommitSequence {
    fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        Ok(Self(<Integer as NotaDecode>::from_nota_block(block)?))
    }
}

impl NotaEncode for CommitSequence {
    fn to_nota(&self) -> String {
        NotaEncode::to_nota(&self.0)
    }
}

impl CommitSequence {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

impl NotaDecode for StateDigest {
    fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        Ok(Self(<Integer as NotaDecode>::from_nota_block(block)?))
    }
}

impl NotaEncode for StateDigest {
    fn to_nota(&self) -> String {
        NotaEncode::to_nota(&self.0)
    }
}

impl StateDigest {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

impl NotaDecode for DatabaseMarker {
    fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        let children = NotaBlock::new(block).expect_children(nota_next::Delimiter::Parenthesis, "parenthesis", "DatabaseMarker", 2)?;
        Ok(Self {
            commit_sequence: <CommitSequence as NotaDecode>::from_nota_block(&children[0])?,
            state_digest: <StateDigest as NotaDecode>::from_nota_block(&children[1])?,
        })
    }
}

impl NotaEncode for DatabaseMarker {
    fn to_nota(&self) -> String {
        let fields = [
            NotaEncode::to_nota(&self.commit_sequence),
            NotaEncode::to_nota(&self.state_digest),
        ];
        format!("({})", fields.join(" "))
    }
}

impl DatabaseMarker {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

impl NotaDecode for SemaReceipt {
    fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        let children = NotaBlock::new(block).expect_children(nota_next::Delimiter::Parenthesis, "parenthesis", "SemaReceipt", 2)?;
        Ok(Self {
            record_identifier: <RecordIdentifier as NotaDecode>::from_nota_block(&children[0])?,
            database_marker: <DatabaseMarker as NotaDecode>::from_nota_block(&children[1])?,
        })
    }
}

impl NotaEncode for SemaReceipt {
    fn to_nota(&self) -> String {
        let fields = [
            NotaEncode::to_nota(&self.record_identifier),
            NotaEncode::to_nota(&self.database_marker),
        ];
        format!("({})", fields.join(" "))
    }
}

impl SemaReceipt {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

impl NotaDecode for ObservedRecords {
    fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        let children = NotaBlock::new(block).expect_children(nota_next::Delimiter::Parenthesis, "parenthesis", "ObservedRecords", 2)?;
        Ok(Self {
            record_set: <RecordSet as NotaDecode>::from_nota_block(&children[0])?,
            database_marker: <DatabaseMarker as NotaDecode>::from_nota_block(&children[1])?,
        })
    }
}

impl NotaEncode for ObservedRecords {
    fn to_nota(&self) -> String {
        let fields = [
            NotaEncode::to_nota(&self.record_set),
            NotaEncode::to_nota(&self.database_marker),
        ];
        format!("({})", fields.join(" "))
    }
}

impl ObservedRecords {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

impl NotaDecode for ErrorReport {
    fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        let children = NotaBlock::new(block).expect_children(nota_next::Delimiter::Parenthesis, "parenthesis", "ErrorReport", 2)?;
        Ok(Self {
            error_message: <ErrorMessage as NotaDecode>::from_nota_block(&children[0])?,
            database_marker: <DatabaseMarker as NotaDecode>::from_nota_block(&children[1])?,
        })
    }
}

impl NotaEncode for ErrorReport {
    fn to_nota(&self) -> String {
        let fields = [
            NotaEncode::to_nota(&self.error_message),
            NotaEncode::to_nota(&self.database_marker),
        ];
        format!("({})", fields.join(" "))
    }
}

impl ErrorReport {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

impl NotaDecode for SignalRejection {
    fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        let children = NotaBlock::new(block).expect_children(nota_next::Delimiter::Parenthesis, "parenthesis", "SignalRejection", 2)?;
        Ok(Self {
            validation_error: <ValidationError as NotaDecode>::from_nota_block(&children[0])?,
            database_marker: <DatabaseMarker as NotaDecode>::from_nota_block(&children[1])?,
        })
    }
}

impl NotaEncode for SignalRejection {
    fn to_nota(&self) -> String {
        let fields = [
            NotaEncode::to_nota(&self.validation_error),
            NotaEncode::to_nota(&self.database_marker),
        ];
        format!("({})", fields.join(" "))
    }
}

impl SignalRejection {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

impl NotaDecode for ValidationError {
    fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        if let Some(variant) = block.demote_to_string() {
            return match variant {
                "EmptyTopic" => Ok(Self::EmptyTopic),
                "EmptyDescription" => Ok(Self::EmptyDescription),
                "EmptyQueryTopic" => Ok(Self::EmptyQueryTopic),
                other => Err(NotaDecodeError::UnknownVariant { enum_name: "ValidationError", variant: other.to_owned() }),
            };
        }
        Err(NotaDecodeError::ExpectedAtom { type_name: "ValidationError" })
    }

}

impl NotaEncode for ValidationError {
    fn to_nota(&self) -> String {
        match self {
            Self::EmptyTopic => "EmptyTopic".to_owned(),
            Self::EmptyDescription => "EmptyDescription".to_owned(),
            Self::EmptyQueryTopic => "EmptyQueryTopic".to_owned(),
        }
    }
}

impl ValidationError {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

impl NotaDecode for MailIdentifier {
    fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        Ok(Self(<Integer as NotaDecode>::from_nota_block(block)?))
    }
}

impl NotaEncode for MailIdentifier {
    fn to_nota(&self) -> String {
        NotaEncode::to_nota(&self.0)
    }
}

impl MailIdentifier {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

impl NotaDecode for ShortHeader {
    fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        Ok(Self(<Integer as NotaDecode>::from_nota_block(block)?))
    }
}

impl NotaEncode for ShortHeader {
    fn to_nota(&self) -> String {
        NotaEncode::to_nota(&self.0)
    }
}

impl ShortHeader {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

impl NotaDecode for SentMail {
    fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        let children = NotaBlock::new(block).expect_children(nota_next::Delimiter::Parenthesis, "parenthesis", "SentMail", 3)?;
        Ok(Self {
            mail_identifier: <MailIdentifier as NotaDecode>::from_nota_block(&children[0])?,
            origin_route: <OriginRoute as NotaDecode>::from_nota_block(&children[1])?,
            short_header: <ShortHeader as NotaDecode>::from_nota_block(&children[2])?,
        })
    }
}

impl NotaEncode for SentMail {
    fn to_nota(&self) -> String {
        let fields = [
            NotaEncode::to_nota(&self.mail_identifier),
            NotaEncode::to_nota(&self.origin_route),
            NotaEncode::to_nota(&self.short_header),
        ];
        format!("({})", fields.join(" "))
    }
}

impl SentMail {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

impl NotaDecode for ProcessedMail {
    fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        let children = NotaBlock::new(block).expect_children(nota_next::Delimiter::Parenthesis, "parenthesis", "ProcessedMail", 3)?;
        Ok(Self {
            mail_identifier: <MailIdentifier as NotaDecode>::from_nota_block(&children[0])?,
            origin_route: <OriginRoute as NotaDecode>::from_nota_block(&children[1])?,
            database_marker: <DatabaseMarker as NotaDecode>::from_nota_block(&children[2])?,
        })
    }
}

impl NotaEncode for ProcessedMail {
    fn to_nota(&self) -> String {
        let fields = [
            NotaEncode::to_nota(&self.mail_identifier),
            NotaEncode::to_nota(&self.origin_route),
            NotaEncode::to_nota(&self.database_marker),
        ];
        format!("({})", fields.join(" "))
    }
}

impl ProcessedMail {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

impl NotaDecode for MailLedgerEvent {
    fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        if let Some(variant) = block.demote_to_string() {
            return Err(NotaDecodeError::UnknownVariant { enum_name: "MailLedgerEvent", variant: variant.to_owned() });
        }
        let children = NotaBlock::new(block).expect_children(nota_next::Delimiter::Parenthesis, "parenthesis", "MailLedgerEvent", 2)?;
        let variant = children[0].demote_to_string().ok_or(NotaDecodeError::ExpectedAtom { type_name: "enum variant" })?;
        match variant {
            "Sent" => Ok(Self::Sent(<SentMail as NotaDecode>::from_nota_block(&children[1])?)),
            "Processed" => Ok(Self::Processed(<ProcessedMail as NotaDecode>::from_nota_block(&children[1])?)),
            other => Err(NotaDecodeError::UnknownVariant { enum_name: "MailLedgerEvent", variant: other.to_owned() }),
        }
    }

}

impl NotaEncode for MailLedgerEvent {
    fn to_nota(&self) -> String {
        match self {
            Self::Sent(payload) => format!("(Sent {})", NotaEncode::to_nota(payload)),
            Self::Processed(payload) => format!("(Processed {})", NotaEncode::to_nota(payload)),
        }
    }
}

impl MailLedgerEvent {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

impl NotaDecode for Entry {
    fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        let children = NotaBlock::new(block).expect_children(nota_next::Delimiter::Parenthesis, "parenthesis", "Entry", 4)?;
        Ok(Self {
            topic: <Topic as NotaDecode>::from_nota_block(&children[0])?,
            kind: <Kind as NotaDecode>::from_nota_block(&children[1])?,
            description: <Description as NotaDecode>::from_nota_block(&children[2])?,
            magnitude: <Magnitude as NotaDecode>::from_nota_block(&children[3])?,
        })
    }
}

impl NotaEncode for Entry {
    fn to_nota(&self) -> String {
        let fields = [
            NotaEncode::to_nota(&self.topic),
            NotaEncode::to_nota(&self.kind),
            NotaEncode::to_nota(&self.description),
            NotaEncode::to_nota(&self.magnitude),
        ];
        format!("({})", fields.join(" "))
    }
}

impl Entry {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

impl NotaDecode for Query {
    fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        let children = NotaBlock::new(block).expect_children(nota_next::Delimiter::Parenthesis, "parenthesis", "Query", 2)?;
        Ok(Self {
            topic: <Topic as NotaDecode>::from_nota_block(&children[0])?,
            kind: <Kind as NotaDecode>::from_nota_block(&children[1])?,
        })
    }
}

impl NotaEncode for Query {
    fn to_nota(&self) -> String {
        let fields = [
            NotaEncode::to_nota(&self.topic),
            NotaEncode::to_nota(&self.kind),
        ];
        format!("({})", fields.join(" "))
    }
}

impl Query {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

impl NotaDecode for RecordSet {
    fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        Ok(Self(<Entry as NotaDecode>::from_nota_block(block)?))
    }
}

impl NotaEncode for RecordSet {
    fn to_nota(&self) -> String {
        NotaEncode::to_nota(&self.0)
    }
}

impl RecordSet {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

impl NotaDecode for Kind {
    fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        if let Some(variant) = block.demote_to_string() {
            return match variant {
                "Decision" => Ok(Self::Decision),
                "Principle" => Ok(Self::Principle),
                "Correction" => Ok(Self::Correction),
                "Clarification" => Ok(Self::Clarification),
                "Constraint" => Ok(Self::Constraint),
                other => Err(NotaDecodeError::UnknownVariant { enum_name: "Kind", variant: other.to_owned() }),
            };
        }
        Err(NotaDecodeError::ExpectedAtom { type_name: "Kind" })
    }

}

impl NotaEncode for Kind {
    fn to_nota(&self) -> String {
        match self {
            Self::Decision => "Decision".to_owned(),
            Self::Principle => "Principle".to_owned(),
            Self::Correction => "Correction".to_owned(),
            Self::Clarification => "Clarification".to_owned(),
            Self::Constraint => "Constraint".to_owned(),
        }
    }
}

impl Kind {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

impl NotaDecode for Magnitude {
    fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        if let Some(variant) = block.demote_to_string() {
            return match variant {
                "Minimum" => Ok(Self::Minimum),
                "VeryLow" => Ok(Self::VeryLow),
                "Low" => Ok(Self::Low),
                "Medium" => Ok(Self::Medium),
                "High" => Ok(Self::High),
                "VeryHigh" => Ok(Self::VeryHigh),
                "Maximum" => Ok(Self::Maximum),
                other => Err(NotaDecodeError::UnknownVariant { enum_name: "Magnitude", variant: other.to_owned() }),
            };
        }
        Err(NotaDecodeError::ExpectedAtom { type_name: "Magnitude" })
    }

}

impl NotaEncode for Magnitude {
    fn to_nota(&self) -> String {
        match self {
            Self::Minimum => "Minimum".to_owned(),
            Self::VeryLow => "VeryLow".to_owned(),
            Self::Low => "Low".to_owned(),
            Self::Medium => "Medium".to_owned(),
            Self::High => "High".to_owned(),
            Self::VeryHigh => "VeryHigh".to_owned(),
            Self::Maximum => "Maximum".to_owned(),
        }
    }
}

impl Magnitude {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

impl NotaDecode for Input {
    fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        if let Some(variant) = block.demote_to_string() {
            return Err(NotaDecodeError::UnknownVariant { enum_name: "Input", variant: variant.to_owned() });
        }
        let children = NotaBlock::new(block).expect_children(nota_next::Delimiter::Parenthesis, "parenthesis", "Input", 2)?;
        let variant = children[0].demote_to_string().ok_or(NotaDecodeError::ExpectedAtom { type_name: "enum variant" })?;
        match variant {
            "Record" => Ok(Self::Record(<Entry as NotaDecode>::from_nota_block(&children[1])?)),
            "Observe" => Ok(Self::Observe(<Query as NotaDecode>::from_nota_block(&children[1])?)),
            other => Err(NotaDecodeError::UnknownVariant { enum_name: "Input", variant: other.to_owned() }),
        }
    }

}

impl NotaEncode for Input {
    fn to_nota(&self) -> String {
        match self {
            Self::Record(payload) => format!("(Record {})", NotaEncode::to_nota(payload)),
            Self::Observe(payload) => format!("(Observe {})", NotaEncode::to_nota(payload)),
        }
    }
}

impl Input {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

impl std::str::FromStr for Input {
    type Err = NotaDecodeError;

    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}

impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

impl NotaDecode for Output {
    fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        if let Some(variant) = block.demote_to_string() {
            return Err(NotaDecodeError::UnknownVariant { enum_name: "Output", variant: variant.to_owned() });
        }
        let children = NotaBlock::new(block).expect_children(nota_next::Delimiter::Parenthesis, "parenthesis", "Output", 2)?;
        let variant = children[0].demote_to_string().ok_or(NotaDecodeError::ExpectedAtom { type_name: "enum variant" })?;
        match variant {
            "RecordAccepted" => Ok(Self::RecordAccepted(<SemaReceipt as NotaDecode>::from_nota_block(&children[1])?)),
            "RecordsObserved" => Ok(Self::RecordsObserved(<ObservedRecords as NotaDecode>::from_nota_block(&children[1])?)),
            "Error" => Ok(Self::Error(<ErrorReport as NotaDecode>::from_nota_block(&children[1])?)),
            "Rejected" => Ok(Self::Rejected(<SignalRejection as NotaDecode>::from_nota_block(&children[1])?)),
            other => Err(NotaDecodeError::UnknownVariant { enum_name: "Output", variant: other.to_owned() }),
        }
    }

}

impl NotaEncode for Output {
    fn to_nota(&self) -> String {
        match self {
            Self::RecordAccepted(payload) => format!("(RecordAccepted {})", NotaEncode::to_nota(payload)),
            Self::RecordsObserved(payload) => format!("(RecordsObserved {})", NotaEncode::to_nota(payload)),
            Self::Error(payload) => format!("(Error {})", NotaEncode::to_nota(payload)),
            Self::Rejected(payload) => format!("(Rejected {})", NotaEncode::to_nota(payload)),
        }
    }
}

impl Output {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

impl std::str::FromStr for Output {
    type Err = NotaDecodeError;

    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}

impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

pub mod short_header {
    pub const INPUT_RECORD: u64 = 0x0000000000000000;
    pub const INPUT_OBSERVE: u64 = 0x0001000000000000;
    pub const OUTPUT_RECORD_ACCEPTED: u64 = 0x0100000000000000;
    pub const OUTPUT_RECORDS_OBSERVED: u64 = 0x0101000000000000;
    pub const OUTPUT_ERROR: u64 = 0x0102000000000000;
    pub const OUTPUT_REJECTED: u64 = 0x0103000000000000;
}

const SIGNAL_SHORT_HEADER_BYTE_COUNT: usize = 8;

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    UnknownHeader { root_enum: &'static str, header: u64 },
    HeaderMismatch { expected: u64, found: u64 },
}

impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => write!(formatter, "signal frame too short: {found} bytes"),
            Self::UnknownHeader { root_enum, header } => write!(formatter, "unknown {root_enum} short header 0x{header:016X}"),
            Self::HeaderMismatch { expected, found } => write!(formatter, "decoded payload header mismatch: expected 0x{expected:016X}, found 0x{found:016X}"),
        }
    }
}

impl std::error::Error for SignalFrameError {}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum InputRoute {
    Record,
    Observe,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum OutputRoute {
    RecordAccepted,
    RecordsObserved,
    Error,
    Rejected,
}

impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::Record(_) => InputRoute::Record,
            Self::Observe(_) => InputRoute::Observe,
        }
    }

    pub fn short_header(&self) -> u64 {
        match self {
            Self::Record(_) => short_header::INPUT_RECORD,
            Self::Observe(_) => short_header::INPUT_OBSERVE,
        }
    }

    pub fn route_from_short_header(header: u64) -> Result<InputRoute, SignalFrameError> {
        match header {
            short_header::INPUT_RECORD => Ok(InputRoute::Record),
            short_header::INPUT_OBSERVE => Ok(InputRoute::Observe),
            _ => Err(SignalFrameError::UnknownHeader { root_enum: "Input", header }),
        }
    }

    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len());
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }

    pub fn decode_signal_frame(frame: &[u8]) -> Result<(InputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort { found: frame.len() });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<Self, rkyv::rancor::Error>(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch { expected, found: header });
        }
        Ok((route, value))
    }
}

impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::RecordAccepted(_) => OutputRoute::RecordAccepted,
            Self::RecordsObserved(_) => OutputRoute::RecordsObserved,
            Self::Error(_) => OutputRoute::Error,
            Self::Rejected(_) => OutputRoute::Rejected,
        }
    }

    pub fn short_header(&self) -> u64 {
        match self {
            Self::RecordAccepted(_) => short_header::OUTPUT_RECORD_ACCEPTED,
            Self::RecordsObserved(_) => short_header::OUTPUT_RECORDS_OBSERVED,
            Self::Error(_) => short_header::OUTPUT_ERROR,
            Self::Rejected(_) => short_header::OUTPUT_REJECTED,
        }
    }

    pub fn route_from_short_header(header: u64) -> Result<OutputRoute, SignalFrameError> {
        match header {
            short_header::OUTPUT_RECORD_ACCEPTED => Ok(OutputRoute::RecordAccepted),
            short_header::OUTPUT_RECORDS_OBSERVED => Ok(OutputRoute::RecordsObserved),
            short_header::OUTPUT_ERROR => Ok(OutputRoute::Error),
            short_header::OUTPUT_REJECTED => Ok(OutputRoute::Rejected),
            _ => Err(SignalFrameError::UnknownHeader { root_enum: "Output", header }),
        }
    }

    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len());
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }

    pub fn decode_signal_frame(frame: &[u8]) -> Result<(OutputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort { found: frame.len() });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<Self, rkyv::rancor::Error>(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch { expected, found: header });
        }
        Ok((route, value))
    }
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub struct MessageIdentifier(pub Integer);

impl NotaDecode for MessageIdentifier {
    fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        Ok(Self(<Integer as NotaDecode>::from_nota_block(block)?))
    }
}

impl NotaEncode for MessageIdentifier {
    fn to_nota(&self) -> String {
        NotaEncode::to_nota(&self.0)
    }
}

impl MessageIdentifier {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(self) -> String {
        <Self as NotaEncode>::to_nota(&self)
    }
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub struct OriginRoute(pub Integer);

impl NotaDecode for OriginRoute {
    fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        Ok(Self(<Integer as NotaDecode>::from_nota_block(block)?))
    }
}

impl NotaEncode for OriginRoute {
    fn to_nota(&self) -> String {
        NotaEncode::to_nota(&self.0)
    }
}

impl OriginRoute {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(self) -> String {
        <Self as NotaEncode>::to_nota(&self)
    }
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum MessageRoot {
    Input,
    Output,
}

pub mod schema {
    #[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
    pub enum Plane<SignalRoot, NexusRoot, SemaRoot> {
        Signal(super::Signal<SignalRoot>),
        Nexus(super::Nexus<NexusRoot>),
        Sema(super::Sema<SemaRoot>),
    }

    impl<SignalRoot, NexusRoot, SemaRoot> Plane<SignalRoot, NexusRoot, SemaRoot> {
        pub fn origin_route(&self) -> super::OriginRoute {
            match self {
                Self::Signal(message) => message.origin_route(),
                Self::Nexus(message) => message.origin_route(),
                Self::Sema(message) => message.origin_route(),
            }
        }
    }
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Signal<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}

impl<Root> Signal<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }

    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }

    pub fn root(&self) -> &Root {
        &self.root
    }

    pub fn into_root(self) -> Root {
        self.root
    }

    pub fn map_root<NextRoot>(self, map: impl FnOnce(Root) -> NextRoot) -> Signal<NextRoot> {
        Signal::new(self.origin_route, map(self.root))
    }
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Nexus<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}

impl<Root> Nexus<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }

    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }

    pub fn root(&self) -> &Root {
        &self.root
    }

    pub fn into_root(self) -> Root {
        self.root
    }

    pub fn map_root<NextRoot>(self, map: impl FnOnce(Root) -> NextRoot) -> Nexus<NextRoot> {
        Nexus::new(self.origin_route, map(self.root))
    }
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Sema<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}

impl<Root> Sema<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }

    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }

    pub fn root(&self) -> &Root {
        &self.root
    }

    pub fn into_root(self) -> Root {
        self.root
    }

    pub fn map_root<NextRoot>(self, map: impl FnOnce(Root) -> NextRoot) -> Sema<NextRoot> {
        Sema::new(self.origin_route, map(self.root))
    }
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MessageSent {
    pub identifier: MessageIdentifier,
    pub origin_route: OriginRoute,
    pub root: MessageRoot,
    pub short_header: Integer,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct NexusMail<Payload> {
    pub identifier: MessageIdentifier,
    pub origin_route: OriginRoute,
    pub payload: Payload,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MessageProcessed<Reply> {
    pub identifier: MessageIdentifier,
    pub origin_route: OriginRoute,
    pub reply: Reply,
}

pub trait MessageSentHook {
    type Error;

    fn message_sent(&mut self, event: MessageSent) -> Result<(), Self::Error>;
}

pub trait MessageProcessedHook<Reply> {
    type Error;

    fn message_processed(&mut self, event: MessageProcessed<Reply>) -> Result<(), Self::Error>;
}

impl MessageSent {
    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }

    pub fn push_to<Hook>(&self, hook: &mut Hook) -> Result<(), Hook::Error>
    where
        Hook: MessageSentHook,
    {
        hook.message_sent(self.clone())
    }
}

impl<Payload> NexusMail<Payload> {
    pub fn new(identifier: MessageIdentifier, origin_route: OriginRoute, payload: Payload) -> Self {
        Self { identifier, origin_route, payload }
    }

    pub fn identifier(&self) -> MessageIdentifier {
        self.identifier
    }

    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }

    pub fn into_payload(self) -> Payload {
        self.payload
    }
}

impl<Reply> MessageProcessed<Reply> {
    pub fn new(identifier: MessageIdentifier, origin_route: OriginRoute, reply: Reply) -> Self {
        Self { identifier, origin_route, reply }
    }

    pub fn identifier(&self) -> MessageIdentifier {
        self.identifier
    }

    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }

    pub fn into_reply(self) -> Reply {
        self.reply
    }

    pub fn push_to<Hook>(&self, hook: &mut Hook) -> Result<(), Hook::Error>
    where
        Hook: MessageProcessedHook<Reply>,
        Reply: Clone,
    {
        hook.message_processed(self.clone())
    }
}

impl Input {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> Signal<Self> {
        Signal::new(origin_route, self)
    }

}

impl signal::Signal<Input> {
    pub fn message_sent(&self, identifier: MessageIdentifier) -> MessageSent {
        MessageSent {
            identifier,
            origin_route: self.origin_route(),
            root: MessageRoot::Input,
            short_header: self.root().short_header(),
        }
    }
}

impl Output {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> Signal<Self> {
        Signal::new(origin_route, self)
    }

}

impl signal::Signal<Output> {
    pub fn message_sent(&self, identifier: MessageIdentifier) -> MessageSent {
        MessageSent {
            identifier,
            origin_route: self.origin_route(),
            root: MessageRoot::Output,
            short_header: self.root().short_header(),
        }
    }
}

pub mod signal {
    pub type Input = super::Input;
    pub type Output = super::Output;
    pub type Signal<Root> = super::Signal<Root>;
}

pub mod nexus {
    pub type Input = super::NexusInput;
    pub type Output = super::NexusOutput;
    pub type Nexus<Root> = super::Nexus<Root>;
}

pub mod sema {
    pub type Input = super::SemaInput;
    pub type Output = super::SemaOutput;
    pub type Sema<Root> = super::Sema<Root>;
}

impl NexusInput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> nexus::Nexus<Self> {
        nexus::Nexus::new(origin_route, self)
    }
}

impl NexusOutput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> nexus::Nexus<Self> {
        nexus::Nexus::new(origin_route, self)
    }
}

impl SemaInput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

impl SemaOutput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

pub trait InputNexus {
    type Reply;
    type Error;

    fn record(&self, mail: NexusMail<Entry>) -> Result<Self::Reply, Self::Error>;
    fn observe(&self, mail: NexusMail<Query>) -> Result<Self::Reply, Self::Error>;
}

impl Input {
    pub fn dispatch_mail_with_nexus<NexusActor>(self, identifier: MessageIdentifier, origin_route: OriginRoute, nexus: &NexusActor) -> Result<MessageProcessed<NexusActor::Reply>, NexusActor::Error>
    where
        NexusActor: InputNexus,
    {
        let reply = match self {
            Self::Record(payload) => nexus.record(NexusMail::new(identifier, origin_route, payload)),
            Self::Observe(payload) => nexus.observe(NexusMail::new(identifier, origin_route, payload)),
        }?;
        Ok(MessageProcessed::new(identifier, origin_route, reply))
    }
}

pub trait OutputNexus {
    type Reply;
    type Error;

    fn record_accepted(&self, mail: NexusMail<SemaReceipt>) -> Result<Self::Reply, Self::Error>;
    fn records_observed(&self, mail: NexusMail<ObservedRecords>) -> Result<Self::Reply, Self::Error>;
    fn error(&self, mail: NexusMail<ErrorReport>) -> Result<Self::Reply, Self::Error>;
    fn rejected(&self, mail: NexusMail<SignalRejection>) -> Result<Self::Reply, Self::Error>;
}

impl Output {
    pub fn dispatch_mail_with_nexus<NexusActor>(self, identifier: MessageIdentifier, origin_route: OriginRoute, nexus: &NexusActor) -> Result<MessageProcessed<NexusActor::Reply>, NexusActor::Error>
    where
        NexusActor: OutputNexus,
    {
        let reply = match self {
            Self::RecordAccepted(payload) => nexus.record_accepted(NexusMail::new(identifier, origin_route, payload)),
            Self::RecordsObserved(payload) => nexus.records_observed(NexusMail::new(identifier, origin_route, payload)),
            Self::Error(payload) => nexus.error(NexusMail::new(identifier, origin_route, payload)),
            Self::Rejected(payload) => nexus.rejected(NexusMail::new(identifier, origin_route, payload)),
        }?;
        Ok(MessageProcessed::new(identifier, origin_route, reply))
    }
}

pub trait NexusEngine {
    fn execute(&self, input: nexus::Nexus<nexus::Input>) -> nexus::Nexus<nexus::Output>;
}

pub trait SemaEngine {
    fn apply(&mut self, input: sema::Sema<sema::Input>) -> sema::Sema<sema::Output>;
}

pub trait UpgradeFrom<Previous>: Sized {
    type Error;

    fn upgrade_from(previous: Previous) -> Result<Self, Self::Error>;
}

pub trait AcceptPrevious<Previous>: UpgradeFrom<Previous> {
    fn accept_previous(previous: Previous) -> Result<Self, Self::Error> {
        Self::upgrade_from(previous)
    }
}

impl<Current, Previous> AcceptPrevious<Previous> for Current where Current: UpgradeFrom<Previous> {}
