// @generated by schema-rust-next

pub type Text = String;
pub type Integer = u64;

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum NotaDecodeError {
    Parse(String),
    ExpectedSingleRoot { found: usize },
    ExpectedDelimited { type_name: &'static str, delimiter: &'static str },
    ExpectedRootCount { type_name: &'static str, expected: usize, found: usize },
    ExpectedAtom { type_name: &'static str },
    UnknownVariant { enum_name: &'static str, variant: String },
    InvalidInteger { value: String },
}

impl std::fmt::Display for NotaDecodeError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Parse(error) => write!(formatter, "{error}"),
            Self::ExpectedSingleRoot { found } => write!(formatter, "expected exactly one NOTA root object, found {found}"),
            Self::ExpectedDelimited { type_name, delimiter } => write!(formatter, "expected {type_name} to be a {delimiter} block"),
            Self::ExpectedRootCount { type_name, expected, found } => write!(formatter, "expected {type_name} to hold {expected} root objects, found {found}"),
            Self::ExpectedAtom { type_name } => write!(formatter, "expected {type_name} atom"),
            Self::UnknownVariant { enum_name, variant } => write!(formatter, "unknown {enum_name} variant {variant}"),
            Self::InvalidInteger { value } => write!(formatter, "invalid integer {value}"),
        }
    }
}

impl std::error::Error for NotaDecodeError {}

pub struct NotaSource<'a> {
    source: &'a str,
}

impl<'a> NotaSource<'a> {
    pub fn new(source: &'a str) -> Self {
        Self { source }
    }

    pub fn parse_root(&self) -> Result<nota_next::Block, NotaDecodeError> {
        let document = nota_next::Document::parse(self.source).map_err(|error| NotaDecodeError::Parse(error.to_string()))?;
        if document.holds_root_objects() != 1 {
            return Err(NotaDecodeError::ExpectedSingleRoot { found: document.holds_root_objects() });
        }
        Ok(document.root_object_at(0).expect("root count checked").clone())
    }
}

pub struct NotaBlock<'a> {
    block: &'a nota_next::Block,
}

impl<'a> NotaBlock<'a> {
    pub fn new(block: &'a nota_next::Block) -> Self {
        Self { block }
    }

    pub fn expect_children(
        &self,
        delimiter: nota_next::Delimiter,
        delimiter_name: &'static str,
        type_name: &'static str,
        expected: usize,
    ) -> Result<&'a [nota_next::Block], NotaDecodeError> {
        match self.block {
            nota_next::Block::Delimited { delimiter: found, root_objects, .. } if *found == delimiter => {
                if root_objects.len() != expected {
                    return Err(NotaDecodeError::ExpectedRootCount { type_name, expected, found: root_objects.len() });
                }
                Ok(root_objects)
            }
            _ => Err(NotaDecodeError::ExpectedDelimited { type_name, delimiter: delimiter_name }),
        }
    }

    pub fn parse_text(&self) -> Result<Text, NotaDecodeError> {
        if let Some(text) = self.block.demote_to_string() {
            return Ok(text.to_owned());
        }
        match self.block {
            nota_next::Block::Delimited { delimiter: nota_next::Delimiter::SquareBracket, root_objects, .. } => {
                root_objects.iter().map(|block| NotaBlock::new(block).parse_text()).collect::<Result<Vec<_>, _>>().map(|parts| parts.join(" "))
            }
            _ => Err(NotaDecodeError::ExpectedDelimited { type_name: "Text", delimiter: "text atom or square bracket" }),
        }
    }

    pub fn parse_integer(&self) -> Result<Integer, NotaDecodeError> {
        let value = self.block.demote_to_string().ok_or(NotaDecodeError::ExpectedAtom { type_name: "Integer" })?;
        value.parse::<Integer>().map_err(|_| NotaDecodeError::InvalidInteger { value: value.to_owned() })
    }
}

pub struct NotaText<'a> {
    value: &'a str,
}

impl<'a> NotaText<'a> {
    pub fn new(value: &'a str) -> Self {
        Self { value }
    }

    pub fn format(&self) -> String {
        if self.value.contains("|]") {
            format!("[{}]", self.value.replace(']', " ]"))
        } else if self.value.chars().any(|character| matches!(character, '[' | ']' | '(' | ')' | '{' | '}' | ';' | '\n')) {
            format!("[|{}|]", self.value)
        } else {
            format!("[{}]", self.value)
        }
    }
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SourcePath(pub Text);

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct LocalPath(pub Text);

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PublicPath(pub Text);

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Import {
    pub source_path: SourcePath,
    pub local_path: LocalPath,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Export {
    pub local_path: LocalPath,
    pub public_path: PublicPath,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SignalReuse {
    pub import: Import,
    pub export: Export,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct NexusReuse {
    pub import: Import,
    pub export: Export,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SemaReuse {
    pub import: Import,
    pub export: Export,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusInput {
    Signal(Input),
    Sema(SemaOutput),
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusOutput {
    Sema(SemaInput),
    Signal(Output),
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SemaInput {
    Record(Entry),
    Observe(Query),
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SemaOutput {
    Recorded(SemaReceipt),
    Observed(ObservedRecords),
    Missed(ErrorReport),
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Topic(pub Text);

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Description(pub Text);

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ErrorMessage(pub Text);

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RecordIdentifier(pub Integer);

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CommitSequence(pub Integer);

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StateDigest(pub Integer);

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DatabaseMarker {
    pub commit_sequence: CommitSequence,
    pub state_digest: StateDigest,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SemaReceipt {
    pub record_identifier: RecordIdentifier,
    pub database_marker: DatabaseMarker,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ObservedRecords {
    pub record_set: RecordSet,
    pub database_marker: DatabaseMarker,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ErrorReport {
    pub error_message: ErrorMessage,
    pub database_marker: DatabaseMarker,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SignalRejection {
    pub validation_error: ValidationError,
    pub database_marker: DatabaseMarker,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ValidationError {
    EmptyTopic,
    EmptyDescription,
    EmptyQueryTopic,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MailIdentifier(pub Integer);

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ShortHeader(pub Integer);

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SentMail {
    pub mail_identifier: MailIdentifier,
    pub short_header: ShortHeader,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ProcessedMail {
    pub mail_identifier: MailIdentifier,
    pub database_marker: DatabaseMarker,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum MailLedgerEvent {
    Sent(SentMail),
    Processed(ProcessedMail),
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Entry {
    pub topic: Topic,
    pub kind: Kind,
    pub description: Description,
    pub magnitude: Magnitude,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Query {
    pub topic: Topic,
    pub kind: Kind,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RecordSet(pub Entry);

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Kind {
    Decision,
    Principle,
    Correction,
    Clarification,
    Constraint,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Magnitude {
    Minimum,
    VeryLow,
    Low,
    Medium,
    High,
    VeryHigh,
    Maximum,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    Record(Entry),
    Observe(Query),
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    RecordAccepted(SemaReceipt),
    RecordsObserved(ObservedRecords),
    Error(ErrorReport),
    Rejected(SignalRejection),
}

impl SourcePath {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        Ok(Self(NotaBlock::new(block).parse_text()?))
    }

    pub fn to_nota(&self) -> String {
        NotaText::new(&self.0).format()
    }
}

impl LocalPath {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        Ok(Self(NotaBlock::new(block).parse_text()?))
    }

    pub fn to_nota(&self) -> String {
        NotaText::new(&self.0).format()
    }
}

impl PublicPath {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        Ok(Self(NotaBlock::new(block).parse_text()?))
    }

    pub fn to_nota(&self) -> String {
        NotaText::new(&self.0).format()
    }
}

impl Import {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        let children = NotaBlock::new(block).expect_children(nota_next::Delimiter::Parenthesis, "parenthesis", "Import", 2)?;
        Ok(Self {
            source_path: SourcePath::from_nota_block(&children[0])?,
            local_path: LocalPath::from_nota_block(&children[1])?,
        })
    }

    pub fn to_nota(&self) -> String {
        let fields = [
            self.source_path.to_nota(),
            self.local_path.to_nota(),
        ];
        format!("({})", fields.join(" "))
    }
}

impl Export {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        let children = NotaBlock::new(block).expect_children(nota_next::Delimiter::Parenthesis, "parenthesis", "Export", 2)?;
        Ok(Self {
            local_path: LocalPath::from_nota_block(&children[0])?,
            public_path: PublicPath::from_nota_block(&children[1])?,
        })
    }

    pub fn to_nota(&self) -> String {
        let fields = [
            self.local_path.to_nota(),
            self.public_path.to_nota(),
        ];
        format!("({})", fields.join(" "))
    }
}

impl SignalReuse {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        let children = NotaBlock::new(block).expect_children(nota_next::Delimiter::Parenthesis, "parenthesis", "SignalReuse", 2)?;
        Ok(Self {
            import: Import::from_nota_block(&children[0])?,
            export: Export::from_nota_block(&children[1])?,
        })
    }

    pub fn to_nota(&self) -> String {
        let fields = [
            self.import.to_nota(),
            self.export.to_nota(),
        ];
        format!("({})", fields.join(" "))
    }
}

impl NexusReuse {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        let children = NotaBlock::new(block).expect_children(nota_next::Delimiter::Parenthesis, "parenthesis", "NexusReuse", 2)?;
        Ok(Self {
            import: Import::from_nota_block(&children[0])?,
            export: Export::from_nota_block(&children[1])?,
        })
    }

    pub fn to_nota(&self) -> String {
        let fields = [
            self.import.to_nota(),
            self.export.to_nota(),
        ];
        format!("({})", fields.join(" "))
    }
}

impl SemaReuse {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        let children = NotaBlock::new(block).expect_children(nota_next::Delimiter::Parenthesis, "parenthesis", "SemaReuse", 2)?;
        Ok(Self {
            import: Import::from_nota_block(&children[0])?,
            export: Export::from_nota_block(&children[1])?,
        })
    }

    pub fn to_nota(&self) -> String {
        let fields = [
            self.import.to_nota(),
            self.export.to_nota(),
        ];
        format!("({})", fields.join(" "))
    }
}

impl NexusInput {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        if let Some(variant) = block.demote_to_string() {
            return Err(NotaDecodeError::UnknownVariant { enum_name: "NexusInput", variant: variant.to_owned() });
        }
        let children = NotaBlock::new(block).expect_children(nota_next::Delimiter::Parenthesis, "parenthesis", "NexusInput", 2)?;
        let variant = children[0].demote_to_string().ok_or(NotaDecodeError::ExpectedAtom { type_name: "enum variant" })?;
        match variant {
            "Signal" => Ok(Self::Signal(Input::from_nota_block(&children[1])?)),
            "Sema" => Ok(Self::Sema(SemaOutput::from_nota_block(&children[1])?)),
            other => Err(NotaDecodeError::UnknownVariant { enum_name: "NexusInput", variant: other.to_owned() }),
        }
    }

    pub fn to_nota(&self) -> String {
        match self {
            Self::Signal(payload) => format!("(Signal {})", payload.to_nota()),
            Self::Sema(payload) => format!("(Sema {})", payload.to_nota()),
        }
    }
}

impl NexusOutput {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        if let Some(variant) = block.demote_to_string() {
            return Err(NotaDecodeError::UnknownVariant { enum_name: "NexusOutput", variant: variant.to_owned() });
        }
        let children = NotaBlock::new(block).expect_children(nota_next::Delimiter::Parenthesis, "parenthesis", "NexusOutput", 2)?;
        let variant = children[0].demote_to_string().ok_or(NotaDecodeError::ExpectedAtom { type_name: "enum variant" })?;
        match variant {
            "Sema" => Ok(Self::Sema(SemaInput::from_nota_block(&children[1])?)),
            "Signal" => Ok(Self::Signal(Output::from_nota_block(&children[1])?)),
            other => Err(NotaDecodeError::UnknownVariant { enum_name: "NexusOutput", variant: other.to_owned() }),
        }
    }

    pub fn to_nota(&self) -> String {
        match self {
            Self::Sema(payload) => format!("(Sema {})", payload.to_nota()),
            Self::Signal(payload) => format!("(Signal {})", payload.to_nota()),
        }
    }
}

impl SemaInput {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        if let Some(variant) = block.demote_to_string() {
            return Err(NotaDecodeError::UnknownVariant { enum_name: "SemaInput", variant: variant.to_owned() });
        }
        let children = NotaBlock::new(block).expect_children(nota_next::Delimiter::Parenthesis, "parenthesis", "SemaInput", 2)?;
        let variant = children[0].demote_to_string().ok_or(NotaDecodeError::ExpectedAtom { type_name: "enum variant" })?;
        match variant {
            "Record" => Ok(Self::Record(Entry::from_nota_block(&children[1])?)),
            "Observe" => Ok(Self::Observe(Query::from_nota_block(&children[1])?)),
            other => Err(NotaDecodeError::UnknownVariant { enum_name: "SemaInput", variant: other.to_owned() }),
        }
    }

    pub fn to_nota(&self) -> String {
        match self {
            Self::Record(payload) => format!("(Record {})", payload.to_nota()),
            Self::Observe(payload) => format!("(Observe {})", payload.to_nota()),
        }
    }
}

impl SemaOutput {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        if let Some(variant) = block.demote_to_string() {
            return Err(NotaDecodeError::UnknownVariant { enum_name: "SemaOutput", variant: variant.to_owned() });
        }
        let children = NotaBlock::new(block).expect_children(nota_next::Delimiter::Parenthesis, "parenthesis", "SemaOutput", 2)?;
        let variant = children[0].demote_to_string().ok_or(NotaDecodeError::ExpectedAtom { type_name: "enum variant" })?;
        match variant {
            "Recorded" => Ok(Self::Recorded(SemaReceipt::from_nota_block(&children[1])?)),
            "Observed" => Ok(Self::Observed(ObservedRecords::from_nota_block(&children[1])?)),
            "Missed" => Ok(Self::Missed(ErrorReport::from_nota_block(&children[1])?)),
            other => Err(NotaDecodeError::UnknownVariant { enum_name: "SemaOutput", variant: other.to_owned() }),
        }
    }

    pub fn to_nota(&self) -> String {
        match self {
            Self::Recorded(payload) => format!("(Recorded {})", payload.to_nota()),
            Self::Observed(payload) => format!("(Observed {})", payload.to_nota()),
            Self::Missed(payload) => format!("(Missed {})", payload.to_nota()),
        }
    }
}

impl Topic {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        Ok(Self(NotaBlock::new(block).parse_text()?))
    }

    pub fn to_nota(&self) -> String {
        NotaText::new(&self.0).format()
    }
}

impl Description {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        Ok(Self(NotaBlock::new(block).parse_text()?))
    }

    pub fn to_nota(&self) -> String {
        NotaText::new(&self.0).format()
    }
}

impl ErrorMessage {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        Ok(Self(NotaBlock::new(block).parse_text()?))
    }

    pub fn to_nota(&self) -> String {
        NotaText::new(&self.0).format()
    }
}

impl RecordIdentifier {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        Ok(Self(NotaBlock::new(block).parse_integer()?))
    }

    pub fn to_nota(&self) -> String {
        self.0.to_string()
    }
}

impl CommitSequence {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        Ok(Self(NotaBlock::new(block).parse_integer()?))
    }

    pub fn to_nota(&self) -> String {
        self.0.to_string()
    }
}

impl StateDigest {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        Ok(Self(NotaBlock::new(block).parse_integer()?))
    }

    pub fn to_nota(&self) -> String {
        self.0.to_string()
    }
}

impl DatabaseMarker {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        let children = NotaBlock::new(block).expect_children(nota_next::Delimiter::Parenthesis, "parenthesis", "DatabaseMarker", 2)?;
        Ok(Self {
            commit_sequence: CommitSequence::from_nota_block(&children[0])?,
            state_digest: StateDigest::from_nota_block(&children[1])?,
        })
    }

    pub fn to_nota(&self) -> String {
        let fields = [
            self.commit_sequence.to_nota(),
            self.state_digest.to_nota(),
        ];
        format!("({})", fields.join(" "))
    }
}

impl SemaReceipt {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        let children = NotaBlock::new(block).expect_children(nota_next::Delimiter::Parenthesis, "parenthesis", "SemaReceipt", 2)?;
        Ok(Self {
            record_identifier: RecordIdentifier::from_nota_block(&children[0])?,
            database_marker: DatabaseMarker::from_nota_block(&children[1])?,
        })
    }

    pub fn to_nota(&self) -> String {
        let fields = [
            self.record_identifier.to_nota(),
            self.database_marker.to_nota(),
        ];
        format!("({})", fields.join(" "))
    }
}

impl ObservedRecords {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        let children = NotaBlock::new(block).expect_children(nota_next::Delimiter::Parenthesis, "parenthesis", "ObservedRecords", 2)?;
        Ok(Self {
            record_set: RecordSet::from_nota_block(&children[0])?,
            database_marker: DatabaseMarker::from_nota_block(&children[1])?,
        })
    }

    pub fn to_nota(&self) -> String {
        let fields = [
            self.record_set.to_nota(),
            self.database_marker.to_nota(),
        ];
        format!("({})", fields.join(" "))
    }
}

impl ErrorReport {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        let children = NotaBlock::new(block).expect_children(nota_next::Delimiter::Parenthesis, "parenthesis", "ErrorReport", 2)?;
        Ok(Self {
            error_message: ErrorMessage::from_nota_block(&children[0])?,
            database_marker: DatabaseMarker::from_nota_block(&children[1])?,
        })
    }

    pub fn to_nota(&self) -> String {
        let fields = [
            self.error_message.to_nota(),
            self.database_marker.to_nota(),
        ];
        format!("({})", fields.join(" "))
    }
}

impl SignalRejection {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        let children = NotaBlock::new(block).expect_children(nota_next::Delimiter::Parenthesis, "parenthesis", "SignalRejection", 2)?;
        Ok(Self {
            validation_error: ValidationError::from_nota_block(&children[0])?,
            database_marker: DatabaseMarker::from_nota_block(&children[1])?,
        })
    }

    pub fn to_nota(&self) -> String {
        let fields = [
            self.validation_error.to_nota(),
            self.database_marker.to_nota(),
        ];
        format!("({})", fields.join(" "))
    }
}

impl ValidationError {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        if let Some(variant) = block.demote_to_string() {
            return match variant {
                "EmptyTopic" => Ok(Self::EmptyTopic),
                "EmptyDescription" => Ok(Self::EmptyDescription),
                "EmptyQueryTopic" => Ok(Self::EmptyQueryTopic),
                other => Err(NotaDecodeError::UnknownVariant { enum_name: "ValidationError", variant: other.to_owned() }),
            };
        }
        Err(NotaDecodeError::ExpectedAtom { type_name: "ValidationError" })
    }

    pub fn to_nota(&self) -> String {
        match self {
            Self::EmptyTopic => "EmptyTopic".to_owned(),
            Self::EmptyDescription => "EmptyDescription".to_owned(),
            Self::EmptyQueryTopic => "EmptyQueryTopic".to_owned(),
        }
    }
}

impl MailIdentifier {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        Ok(Self(NotaBlock::new(block).parse_integer()?))
    }

    pub fn to_nota(&self) -> String {
        self.0.to_string()
    }
}

impl ShortHeader {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        Ok(Self(NotaBlock::new(block).parse_integer()?))
    }

    pub fn to_nota(&self) -> String {
        self.0.to_string()
    }
}

impl SentMail {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        let children = NotaBlock::new(block).expect_children(nota_next::Delimiter::Parenthesis, "parenthesis", "SentMail", 2)?;
        Ok(Self {
            mail_identifier: MailIdentifier::from_nota_block(&children[0])?,
            short_header: ShortHeader::from_nota_block(&children[1])?,
        })
    }

    pub fn to_nota(&self) -> String {
        let fields = [
            self.mail_identifier.to_nota(),
            self.short_header.to_nota(),
        ];
        format!("({})", fields.join(" "))
    }
}

impl ProcessedMail {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        let children = NotaBlock::new(block).expect_children(nota_next::Delimiter::Parenthesis, "parenthesis", "ProcessedMail", 2)?;
        Ok(Self {
            mail_identifier: MailIdentifier::from_nota_block(&children[0])?,
            database_marker: DatabaseMarker::from_nota_block(&children[1])?,
        })
    }

    pub fn to_nota(&self) -> String {
        let fields = [
            self.mail_identifier.to_nota(),
            self.database_marker.to_nota(),
        ];
        format!("({})", fields.join(" "))
    }
}

impl MailLedgerEvent {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        if let Some(variant) = block.demote_to_string() {
            return Err(NotaDecodeError::UnknownVariant { enum_name: "MailLedgerEvent", variant: variant.to_owned() });
        }
        let children = NotaBlock::new(block).expect_children(nota_next::Delimiter::Parenthesis, "parenthesis", "MailLedgerEvent", 2)?;
        let variant = children[0].demote_to_string().ok_or(NotaDecodeError::ExpectedAtom { type_name: "enum variant" })?;
        match variant {
            "Sent" => Ok(Self::Sent(SentMail::from_nota_block(&children[1])?)),
            "Processed" => Ok(Self::Processed(ProcessedMail::from_nota_block(&children[1])?)),
            other => Err(NotaDecodeError::UnknownVariant { enum_name: "MailLedgerEvent", variant: other.to_owned() }),
        }
    }

    pub fn to_nota(&self) -> String {
        match self {
            Self::Sent(payload) => format!("(Sent {})", payload.to_nota()),
            Self::Processed(payload) => format!("(Processed {})", payload.to_nota()),
        }
    }
}

impl Entry {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        let children = NotaBlock::new(block).expect_children(nota_next::Delimiter::Parenthesis, "parenthesis", "Entry", 4)?;
        Ok(Self {
            topic: Topic::from_nota_block(&children[0])?,
            kind: Kind::from_nota_block(&children[1])?,
            description: Description::from_nota_block(&children[2])?,
            magnitude: Magnitude::from_nota_block(&children[3])?,
        })
    }

    pub fn to_nota(&self) -> String {
        let fields = [
            self.topic.to_nota(),
            self.kind.to_nota(),
            self.description.to_nota(),
            self.magnitude.to_nota(),
        ];
        format!("({})", fields.join(" "))
    }
}

impl Query {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        let children = NotaBlock::new(block).expect_children(nota_next::Delimiter::Parenthesis, "parenthesis", "Query", 2)?;
        Ok(Self {
            topic: Topic::from_nota_block(&children[0])?,
            kind: Kind::from_nota_block(&children[1])?,
        })
    }

    pub fn to_nota(&self) -> String {
        let fields = [
            self.topic.to_nota(),
            self.kind.to_nota(),
        ];
        format!("({})", fields.join(" "))
    }
}

impl RecordSet {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        Ok(Self(Entry::from_nota_block(block)?))
    }

    pub fn to_nota(&self) -> String {
        self.0.to_nota()
    }
}

impl Kind {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        if let Some(variant) = block.demote_to_string() {
            return match variant {
                "Decision" => Ok(Self::Decision),
                "Principle" => Ok(Self::Principle),
                "Correction" => Ok(Self::Correction),
                "Clarification" => Ok(Self::Clarification),
                "Constraint" => Ok(Self::Constraint),
                other => Err(NotaDecodeError::UnknownVariant { enum_name: "Kind", variant: other.to_owned() }),
            };
        }
        Err(NotaDecodeError::ExpectedAtom { type_name: "Kind" })
    }

    pub fn to_nota(&self) -> String {
        match self {
            Self::Decision => "Decision".to_owned(),
            Self::Principle => "Principle".to_owned(),
            Self::Correction => "Correction".to_owned(),
            Self::Clarification => "Clarification".to_owned(),
            Self::Constraint => "Constraint".to_owned(),
        }
    }
}

impl Magnitude {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        if let Some(variant) = block.demote_to_string() {
            return match variant {
                "Minimum" => Ok(Self::Minimum),
                "VeryLow" => Ok(Self::VeryLow),
                "Low" => Ok(Self::Low),
                "Medium" => Ok(Self::Medium),
                "High" => Ok(Self::High),
                "VeryHigh" => Ok(Self::VeryHigh),
                "Maximum" => Ok(Self::Maximum),
                other => Err(NotaDecodeError::UnknownVariant { enum_name: "Magnitude", variant: other.to_owned() }),
            };
        }
        Err(NotaDecodeError::ExpectedAtom { type_name: "Magnitude" })
    }

    pub fn to_nota(&self) -> String {
        match self {
            Self::Minimum => "Minimum".to_owned(),
            Self::VeryLow => "VeryLow".to_owned(),
            Self::Low => "Low".to_owned(),
            Self::Medium => "Medium".to_owned(),
            Self::High => "High".to_owned(),
            Self::VeryHigh => "VeryHigh".to_owned(),
            Self::Maximum => "Maximum".to_owned(),
        }
    }
}

impl Input {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        if let Some(variant) = block.demote_to_string() {
            return Err(NotaDecodeError::UnknownVariant { enum_name: "Input", variant: variant.to_owned() });
        }
        let children = NotaBlock::new(block).expect_children(nota_next::Delimiter::Parenthesis, "parenthesis", "Input", 2)?;
        let variant = children[0].demote_to_string().ok_or(NotaDecodeError::ExpectedAtom { type_name: "enum variant" })?;
        match variant {
            "Record" => Ok(Self::Record(Entry::from_nota_block(&children[1])?)),
            "Observe" => Ok(Self::Observe(Query::from_nota_block(&children[1])?)),
            other => Err(NotaDecodeError::UnknownVariant { enum_name: "Input", variant: other.to_owned() }),
        }
    }

    pub fn to_nota(&self) -> String {
        match self {
            Self::Record(payload) => format!("(Record {})", payload.to_nota()),
            Self::Observe(payload) => format!("(Observe {})", payload.to_nota()),
        }
    }
}

impl std::str::FromStr for Input {
    type Err = NotaDecodeError;

    fn from_str(source: &str) -> Result<Self, Self::Err> {
        let root = NotaSource::new(source).parse_root()?;
        Self::from_nota_block(&root)
    }
}

impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&self.to_nota())
    }
}

impl Output {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        if let Some(variant) = block.demote_to_string() {
            return Err(NotaDecodeError::UnknownVariant { enum_name: "Output", variant: variant.to_owned() });
        }
        let children = NotaBlock::new(block).expect_children(nota_next::Delimiter::Parenthesis, "parenthesis", "Output", 2)?;
        let variant = children[0].demote_to_string().ok_or(NotaDecodeError::ExpectedAtom { type_name: "enum variant" })?;
        match variant {
            "RecordAccepted" => Ok(Self::RecordAccepted(SemaReceipt::from_nota_block(&children[1])?)),
            "RecordsObserved" => Ok(Self::RecordsObserved(ObservedRecords::from_nota_block(&children[1])?)),
            "Error" => Ok(Self::Error(ErrorReport::from_nota_block(&children[1])?)),
            "Rejected" => Ok(Self::Rejected(SignalRejection::from_nota_block(&children[1])?)),
            other => Err(NotaDecodeError::UnknownVariant { enum_name: "Output", variant: other.to_owned() }),
        }
    }

    pub fn to_nota(&self) -> String {
        match self {
            Self::RecordAccepted(payload) => format!("(RecordAccepted {})", payload.to_nota()),
            Self::RecordsObserved(payload) => format!("(RecordsObserved {})", payload.to_nota()),
            Self::Error(payload) => format!("(Error {})", payload.to_nota()),
            Self::Rejected(payload) => format!("(Rejected {})", payload.to_nota()),
        }
    }
}

impl std::str::FromStr for Output {
    type Err = NotaDecodeError;

    fn from_str(source: &str) -> Result<Self, Self::Err> {
        let root = NotaSource::new(source).parse_root()?;
        Self::from_nota_block(&root)
    }
}

impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&self.to_nota())
    }
}

pub mod short_header {
    pub const INPUT_RECORD: u64 = 0x0000000000000000;
    pub const INPUT_OBSERVE: u64 = 0x0001000000000000;
    pub const OUTPUT_RECORD_ACCEPTED: u64 = 0x0100000000000000;
    pub const OUTPUT_RECORDS_OBSERVED: u64 = 0x0101000000000000;
    pub const OUTPUT_ERROR: u64 = 0x0102000000000000;
    pub const OUTPUT_REJECTED: u64 = 0x0103000000000000;
}

const SIGNAL_SHORT_HEADER_BYTE_COUNT: usize = 8;

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    UnknownHeader { root_enum: &'static str, header: u64 },
    HeaderMismatch { expected: u64, found: u64 },
}

impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => write!(formatter, "signal frame too short: {found} bytes"),
            Self::UnknownHeader { root_enum, header } => write!(formatter, "unknown {root_enum} short header 0x{header:016X}"),
            Self::HeaderMismatch { expected, found } => write!(formatter, "decoded payload header mismatch: expected 0x{expected:016X}, found 0x{found:016X}"),
        }
    }
}

impl std::error::Error for SignalFrameError {}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum InputRoute {
    Record,
    Observe,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum OutputRoute {
    RecordAccepted,
    RecordsObserved,
    Error,
    Rejected,
}

impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::Record(_) => InputRoute::Record,
            Self::Observe(_) => InputRoute::Observe,
        }
    }

    pub fn short_header(&self) -> u64 {
        match self {
            Self::Record(_) => short_header::INPUT_RECORD,
            Self::Observe(_) => short_header::INPUT_OBSERVE,
        }
    }

    pub fn route_from_short_header(header: u64) -> Result<InputRoute, SignalFrameError> {
        match header {
            short_header::INPUT_RECORD => Ok(InputRoute::Record),
            short_header::INPUT_OBSERVE => Ok(InputRoute::Observe),
            _ => Err(SignalFrameError::UnknownHeader { root_enum: "Input", header }),
        }
    }

    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len());
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }

    pub fn decode_signal_frame(frame: &[u8]) -> Result<(InputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort { found: frame.len() });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<Self, rkyv::rancor::Error>(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch { expected, found: header });
        }
        Ok((route, value))
    }
}

impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::RecordAccepted(_) => OutputRoute::RecordAccepted,
            Self::RecordsObserved(_) => OutputRoute::RecordsObserved,
            Self::Error(_) => OutputRoute::Error,
            Self::Rejected(_) => OutputRoute::Rejected,
        }
    }

    pub fn short_header(&self) -> u64 {
        match self {
            Self::RecordAccepted(_) => short_header::OUTPUT_RECORD_ACCEPTED,
            Self::RecordsObserved(_) => short_header::OUTPUT_RECORDS_OBSERVED,
            Self::Error(_) => short_header::OUTPUT_ERROR,
            Self::Rejected(_) => short_header::OUTPUT_REJECTED,
        }
    }

    pub fn route_from_short_header(header: u64) -> Result<OutputRoute, SignalFrameError> {
        match header {
            short_header::OUTPUT_RECORD_ACCEPTED => Ok(OutputRoute::RecordAccepted),
            short_header::OUTPUT_RECORDS_OBSERVED => Ok(OutputRoute::RecordsObserved),
            short_header::OUTPUT_ERROR => Ok(OutputRoute::Error),
            short_header::OUTPUT_REJECTED => Ok(OutputRoute::Rejected),
            _ => Err(SignalFrameError::UnknownHeader { root_enum: "Output", header }),
        }
    }

    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len());
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }

    pub fn decode_signal_frame(frame: &[u8]) -> Result<(OutputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort { found: frame.len() });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<Self, rkyv::rancor::Error>(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch { expected, found: header });
        }
        Ok((route, value))
    }
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub struct MessageIdentifier(pub Integer);

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum MessageRoot {
    Input,
    Output,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MessageSent {
    pub identifier: MessageIdentifier,
    pub root: MessageRoot,
    pub short_header: Integer,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct NexusMail<Payload> {
    pub identifier: MessageIdentifier,
    pub payload: Payload,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MessageProcessed<Reply> {
    pub identifier: MessageIdentifier,
    pub reply: Reply,
}

pub trait MessageSentHook {
    type Error;

    fn message_sent(&mut self, event: MessageSent) -> Result<(), Self::Error>;
}

pub trait MessageProcessedHook<Reply> {
    type Error;

    fn message_processed(&mut self, event: MessageProcessed<Reply>) -> Result<(), Self::Error>;
}

impl MessageSent {
    pub fn push_to<Hook>(&self, hook: &mut Hook) -> Result<(), Hook::Error>
    where
        Hook: MessageSentHook,
    {
        hook.message_sent(self.clone())
    }
}

impl<Payload> NexusMail<Payload> {
    pub fn new(identifier: MessageIdentifier, payload: Payload) -> Self {
        Self { identifier, payload }
    }

    pub fn identifier(&self) -> MessageIdentifier {
        self.identifier
    }

    pub fn into_payload(self) -> Payload {
        self.payload
    }
}

impl<Reply> MessageProcessed<Reply> {
    pub fn new(identifier: MessageIdentifier, reply: Reply) -> Self {
        Self { identifier, reply }
    }

    pub fn identifier(&self) -> MessageIdentifier {
        self.identifier
    }

    pub fn into_reply(self) -> Reply {
        self.reply
    }

    pub fn push_to<Hook>(&self, hook: &mut Hook) -> Result<(), Hook::Error>
    where
        Hook: MessageProcessedHook<Reply>,
        Reply: Clone,
    {
        hook.message_processed(self.clone())
    }
}

impl Input {
    pub fn message_sent(&self, identifier: MessageIdentifier) -> MessageSent {
        MessageSent {
            identifier,
            root: MessageRoot::Input,
            short_header: self.short_header(),
        }
    }
}

impl Output {
    pub fn message_sent(&self, identifier: MessageIdentifier) -> MessageSent {
        MessageSent {
            identifier,
            root: MessageRoot::Output,
            short_header: self.short_header(),
        }
    }
}

pub trait InputNexus {
    type Reply;
    type Error;

    fn record(&self, mail: NexusMail<Entry>) -> Result<Self::Reply, Self::Error>;
    fn observe(&self, mail: NexusMail<Query>) -> Result<Self::Reply, Self::Error>;
}

impl Input {
    pub fn dispatch_mail_with_nexus<Nexus>(self, identifier: MessageIdentifier, nexus: &Nexus) -> Result<MessageProcessed<Nexus::Reply>, Nexus::Error>
    where
        Nexus: InputNexus,
    {
        let reply = match self {
            Self::Record(payload) => nexus.record(NexusMail::new(identifier, payload)),
            Self::Observe(payload) => nexus.observe(NexusMail::new(identifier, payload)),
        }?;
        Ok(MessageProcessed::new(identifier, reply))
    }
}

pub trait OutputNexus {
    type Reply;
    type Error;

    fn record_accepted(&self, mail: NexusMail<SemaReceipt>) -> Result<Self::Reply, Self::Error>;
    fn records_observed(&self, mail: NexusMail<ObservedRecords>) -> Result<Self::Reply, Self::Error>;
    fn error(&self, mail: NexusMail<ErrorReport>) -> Result<Self::Reply, Self::Error>;
    fn rejected(&self, mail: NexusMail<SignalRejection>) -> Result<Self::Reply, Self::Error>;
}

impl Output {
    pub fn dispatch_mail_with_nexus<Nexus>(self, identifier: MessageIdentifier, nexus: &Nexus) -> Result<MessageProcessed<Nexus::Reply>, Nexus::Error>
    where
        Nexus: OutputNexus,
    {
        let reply = match self {
            Self::RecordAccepted(payload) => nexus.record_accepted(NexusMail::new(identifier, payload)),
            Self::RecordsObserved(payload) => nexus.records_observed(NexusMail::new(identifier, payload)),
            Self::Error(payload) => nexus.error(NexusMail::new(identifier, payload)),
            Self::Rejected(payload) => nexus.rejected(NexusMail::new(identifier, payload)),
        }?;
        Ok(MessageProcessed::new(identifier, reply))
    }
}

pub trait NexusEngine {
    fn execute(&self, input: NexusInput) -> NexusOutput;
}

pub trait SemaEngine {
    fn apply(&mut self, input: SemaInput) -> SemaOutput;
}

pub trait UpgradeFrom<Previous>: Sized {
    type Error;

    fn upgrade_from(previous: Previous) -> Result<Self, Self::Error>;
}

pub trait AcceptPrevious<Previous>: UpgradeFrom<Previous> {
    fn accept_previous(previous: Previous) -> Result<Self, Self::Error> {
        Self::upgrade_from(previous)
    }
}

impl<Current, Previous> AcceptPrevious<Previous> for Current where Current: UpgradeFrom<Previous> {}
