// @generated by schema-rust-next

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
pub use crate::schema::signal::Input as SignalInput;
#[rustfmt::skip]
pub use crate::schema::signal::Output as SignalOutput;
#[rustfmt::skip]
pub use crate::schema::sema::ReadInput as SemaReadInput;
#[rustfmt::skip]
pub use crate::schema::sema::ReadOutput as SemaReadOutput;
#[rustfmt::skip]
pub use crate::schema::sema::WriteOutput as SemaWriteOutput;
#[rustfmt::skip]
pub use crate::schema::signal::Records as Records;
#[rustfmt::skip]
pub use crate::schema::signal::RecordCount as RecordCount;
#[rustfmt::skip]
pub use crate::schema::signal::StashHandle as StashHandle;
#[rustfmt::skip]
pub use crate::schema::signal::DatabaseMarker as DatabaseMarker;
#[rustfmt::skip]
pub use crate::schema::signal::Statement as Statement;
#[rustfmt::skip]
pub use crate::schema::signal::Entry as Entry;
#[rustfmt::skip]
pub use crate::schema::signal::Clarification as Clarification;
#[rustfmt::skip]
pub use crate::schema::signal::Supersession as Supersession;
#[rustfmt::skip]
pub use crate::schema::signal::Retirement as Retirement;
#[rustfmt::skip]
pub use crate::schema::signal::SemaReceipt as SemaReceipt;
#[rustfmt::skip]
pub use crate::schema::signal::ClarificationReceipt as ClarificationReceipt;
#[rustfmt::skip]
pub use crate::schema::signal::SupersessionReceipt as SupersessionReceipt;
#[rustfmt::skip]
pub use crate::schema::signal::RetirementReceipt as RetirementReceipt;
#[rustfmt::skip]
pub use crate::schema::signal::GuardianRejection as GuardianRejection;
#[rustfmt::skip]
pub use crate::schema::signal::GuardianRejectionReason as GuardianRejectionReason;
#[rustfmt::skip]
pub use crate::schema::signal::Explanation as Explanation;
#[rustfmt::skip]
pub use crate::schema::signal::ErrorReport as ErrorReport;
#[rustfmt::skip]
pub use crate::schema::signal::Query as Query;
#[rustfmt::skip]
pub use crate::schema::signal::SubscriptionToken as SubscriptionToken;
#[rustfmt::skip]
pub use crate::schema::signal::IntentSubscription as IntentSubscription;
#[rustfmt::skip]
pub use crate::schema::signal::RecordIdentifier as RecordIdentifier;
#[rustfmt::skip]
pub use crate::schema::signal::CertaintyChange as CertaintyChange;
#[rustfmt::skip]
pub use crate::schema::signal::ImportanceBump as ImportanceBump;
#[rustfmt::skip]
pub use crate::schema::signal::RecordChange as RecordChange;
#[rustfmt::skip]
pub use crate::schema::signal::ReferentRegistration as ReferentRegistration;
#[rustfmt::skip]
pub use crate::schema::signal::RemovalCandidateCollection as RemovalCandidateCollection;
#[rustfmt::skip]
pub use crate::schema::signal::RemovalCandidatesCollection as RemovalCandidatesCollection;
#[rustfmt::skip]
pub use crate::schema::signal::ObserverFilter as ObserverFilter;
#[rustfmt::skip]
pub use crate::schema::signal::ObserverSubscription as ObserverSubscription;
#[rustfmt::skip]
pub use crate::schema::signal::ObserverRetraction as ObserverRetraction;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota_next::{NotaDecode, NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SignalArrived(SignalInput);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SemaWriteCompleted(SemaWriteOutput);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SemaReadCompleted(SemaReadOutput);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EffectCompleted(NexusEffectResult);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum CommandSemaWrite {
    Record(Record),
    Remove(Remove),
    ChangeCertainty(ChangeCertainty),
    BumpImportance(BumpImportance),
    ChangeRecord(ChangeRecord),
    RegisterReferent(RegisterReferent),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Record(Entry);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Remove(RecordIdentifier);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ChangeCertainty(CertaintyChange);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct BumpImportance(ImportanceBump);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ChangeRecord(RecordChange);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RegisterReferent(ReferentRegistration);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CommandSemaRead(SemaReadInput);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ReplyToSignal(SignalOutput);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CommandEffect(NexusEffectCommand);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Continue(NexusWork);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusWork {
    SignalArrived(SignalArrived),
    SemaWriteCompleted(SemaWriteCompleted),
    SemaReadCompleted(SemaReadCompleted),
    EffectCompleted(EffectCompleted),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusAction {
    CommandSemaWrite(CommandSemaWrite),
    CommandSemaRead(CommandSemaRead),
    ReplyToSignal(ReplyToSignal),
    CommandEffect(CommandEffect),
    Continue(Continue),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusEffectCommand {
    Stash(Stash),
    ClassifyState(ClassifyState),
    GuardRecord(GuardRecord),
    Propose(Propose),
    Clarify(Clarify),
    Supersede(Supersede),
    Retire(Retire),
    OpenIntentSubscription(OpenIntentSubscription),
    CollectRemovalCandidates(CollectRemovalCandidates),
    OpenObserverTap(OpenObserverTap),
    CloseObserverTap(CloseObserverTap),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Stash(StashRequest);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ClassifyState(Statement);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct GuardRecord(Entry);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Propose(Entry);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Clarify(Clarification);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Supersede(Supersession);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Retire(Retirement);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct OpenIntentSubscription(Query);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CollectRemovalCandidates(RemovalCandidateCollection);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct OpenObserverTap(ObserverFilter);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CloseObserverTap(SubscriptionToken);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusEffectResult {
    Stashed(Stashed),
    StateClassified(StateClassified),
    Recorded(Recorded),
    Proposed(Proposed),
    Clarified(Clarified),
    Superseded(Superseded),
    Retired(Retired),
    GuardianRejected(GuardianRejected),
    OperationFailed(OperationFailed),
    IntentSubscriptionOpened(IntentSubscriptionOpened),
    RemovalCandidatesCollected(RemovalCandidatesCollected),
    ObserverTapOpened(ObserverTapOpened),
    ObserverTapClosed(ObserverTapClosed),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Stashed(StashResult);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StateClassified(Entry);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Recorded(SemaReceipt);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Proposed(SemaReceipt);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Clarified(ClarificationReceipt);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Superseded(SupersessionReceipt);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Retired(RetirementReceipt);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct GuardianRejected(GuardianRejection);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct OperationFailed(ErrorReport);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct IntentSubscriptionOpened(IntentSubscription);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RemovalCandidatesCollected(RemovalCandidatesCollection);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ObserverTapOpened(ObserverSubscription);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ObserverTapClosed(ObserverRetraction);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StashRequest {
    pub records: Records,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StashResult {
    pub stash_handle: StashHandle,
    pub record_count: RecordCount,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum GuardianVerdict {
    Accept,
    Reject(Reject),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Reject {
    pub guardian_rejection_reason: GuardianRejectionReason,
    pub explanation: Explanation,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    SignalArrived(SignalArrived),
    SemaWriteCompleted(SemaWriteCompleted),
    SemaReadCompleted(SemaReadCompleted),
    EffectCompleted(EffectCompleted),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    CommandSemaWrite(CommandSemaWrite),
    CommandSemaRead(CommandSemaRead),
    ReplyToSignal(ReplyToSignal),
    CommandEffect(CommandEffect),
    Continue(Continue),
}

#[rustfmt::skip]
impl SignalArrived {
    pub fn new(payload: SignalInput) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SignalInput {
        &self.0
    }
    pub fn into_payload(self) -> SignalInput {
        self.0
    }
}
#[rustfmt::skip]
impl From<SignalInput> for SignalArrived {
    fn from(payload: SignalInput) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SemaWriteCompleted {
    pub fn new(payload: SemaWriteOutput) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SemaWriteOutput {
        &self.0
    }
    pub fn into_payload(self) -> SemaWriteOutput {
        self.0
    }
}
#[rustfmt::skip]
impl From<SemaWriteOutput> for SemaWriteCompleted {
    fn from(payload: SemaWriteOutput) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SemaReadCompleted {
    pub fn new(payload: SemaReadOutput) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SemaReadOutput {
        &self.0
    }
    pub fn into_payload(self) -> SemaReadOutput {
        self.0
    }
}
#[rustfmt::skip]
impl From<SemaReadOutput> for SemaReadCompleted {
    fn from(payload: SemaReadOutput) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl EffectCompleted {
    pub fn new(payload: NexusEffectResult) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &NexusEffectResult {
        &self.0
    }
    pub fn into_payload(self) -> NexusEffectResult {
        self.0
    }
}
#[rustfmt::skip]
impl From<NexusEffectResult> for EffectCompleted {
    fn from(payload: NexusEffectResult) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Record {
    pub fn new(payload: Entry) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Entry {
        &self.0
    }
    pub fn into_payload(self) -> Entry {
        self.0
    }
}
#[rustfmt::skip]
impl From<Entry> for Record {
    fn from(payload: Entry) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Remove {
    pub fn new(payload: RecordIdentifier) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RecordIdentifier {
        &self.0
    }
    pub fn into_payload(self) -> RecordIdentifier {
        self.0
    }
}
#[rustfmt::skip]
impl From<RecordIdentifier> for Remove {
    fn from(payload: RecordIdentifier) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ChangeCertainty {
    pub fn new(payload: CertaintyChange) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &CertaintyChange {
        &self.0
    }
    pub fn into_payload(self) -> CertaintyChange {
        self.0
    }
}
#[rustfmt::skip]
impl From<CertaintyChange> for ChangeCertainty {
    fn from(payload: CertaintyChange) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl BumpImportance {
    pub fn new(payload: ImportanceBump) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ImportanceBump {
        &self.0
    }
    pub fn into_payload(self) -> ImportanceBump {
        self.0
    }
}
#[rustfmt::skip]
impl From<ImportanceBump> for BumpImportance {
    fn from(payload: ImportanceBump) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ChangeRecord {
    pub fn new(payload: RecordChange) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RecordChange {
        &self.0
    }
    pub fn into_payload(self) -> RecordChange {
        self.0
    }
}
#[rustfmt::skip]
impl From<RecordChange> for ChangeRecord {
    fn from(payload: RecordChange) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RegisterReferent {
    pub fn new(payload: ReferentRegistration) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ReferentRegistration {
        &self.0
    }
    pub fn into_payload(self) -> ReferentRegistration {
        self.0
    }
}
#[rustfmt::skip]
impl From<ReferentRegistration> for RegisterReferent {
    fn from(payload: ReferentRegistration) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CommandSemaRead {
    pub fn new(payload: SemaReadInput) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SemaReadInput {
        &self.0
    }
    pub fn into_payload(self) -> SemaReadInput {
        self.0
    }
}
#[rustfmt::skip]
impl From<SemaReadInput> for CommandSemaRead {
    fn from(payload: SemaReadInput) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ReplyToSignal {
    pub fn new(payload: SignalOutput) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SignalOutput {
        &self.0
    }
    pub fn into_payload(self) -> SignalOutput {
        self.0
    }
}
#[rustfmt::skip]
impl From<SignalOutput> for ReplyToSignal {
    fn from(payload: SignalOutput) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CommandEffect {
    pub fn new(payload: NexusEffectCommand) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &NexusEffectCommand {
        &self.0
    }
    pub fn into_payload(self) -> NexusEffectCommand {
        self.0
    }
}
#[rustfmt::skip]
impl From<NexusEffectCommand> for CommandEffect {
    fn from(payload: NexusEffectCommand) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Continue {
    pub fn new(payload: NexusWork) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &NexusWork {
        &self.0
    }
    pub fn into_payload(self) -> NexusWork {
        self.0
    }
}
#[rustfmt::skip]
impl From<NexusWork> for Continue {
    fn from(payload: NexusWork) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Stash {
    pub fn new(payload: StashRequest) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &StashRequest {
        &self.0
    }
    pub fn into_payload(self) -> StashRequest {
        self.0
    }
}
#[rustfmt::skip]
impl From<StashRequest> for Stash {
    fn from(payload: StashRequest) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ClassifyState {
    pub fn new(payload: Statement) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Statement {
        &self.0
    }
    pub fn into_payload(self) -> Statement {
        self.0
    }
}
#[rustfmt::skip]
impl From<Statement> for ClassifyState {
    fn from(payload: Statement) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl GuardRecord {
    pub fn new(payload: Entry) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Entry {
        &self.0
    }
    pub fn into_payload(self) -> Entry {
        self.0
    }
}
#[rustfmt::skip]
impl From<Entry> for GuardRecord {
    fn from(payload: Entry) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Propose {
    pub fn new(payload: Entry) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Entry {
        &self.0
    }
    pub fn into_payload(self) -> Entry {
        self.0
    }
}
#[rustfmt::skip]
impl From<Entry> for Propose {
    fn from(payload: Entry) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Clarify {
    pub fn new(payload: Clarification) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Clarification {
        &self.0
    }
    pub fn into_payload(self) -> Clarification {
        self.0
    }
}
#[rustfmt::skip]
impl From<Clarification> for Clarify {
    fn from(payload: Clarification) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Supersede {
    pub fn new(payload: Supersession) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Supersession {
        &self.0
    }
    pub fn into_payload(self) -> Supersession {
        self.0
    }
}
#[rustfmt::skip]
impl From<Supersession> for Supersede {
    fn from(payload: Supersession) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Retire {
    pub fn new(payload: Retirement) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Retirement {
        &self.0
    }
    pub fn into_payload(self) -> Retirement {
        self.0
    }
}
#[rustfmt::skip]
impl From<Retirement> for Retire {
    fn from(payload: Retirement) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl OpenIntentSubscription {
    pub fn new(payload: Query) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Query {
        &self.0
    }
    pub fn into_payload(self) -> Query {
        self.0
    }
}
#[rustfmt::skip]
impl From<Query> for OpenIntentSubscription {
    fn from(payload: Query) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CollectRemovalCandidates {
    pub fn new(payload: RemovalCandidateCollection) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RemovalCandidateCollection {
        &self.0
    }
    pub fn into_payload(self) -> RemovalCandidateCollection {
        self.0
    }
}
#[rustfmt::skip]
impl From<RemovalCandidateCollection> for CollectRemovalCandidates {
    fn from(payload: RemovalCandidateCollection) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl OpenObserverTap {
    pub fn new(payload: ObserverFilter) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ObserverFilter {
        &self.0
    }
    pub fn into_payload(self) -> ObserverFilter {
        self.0
    }
}
#[rustfmt::skip]
impl From<ObserverFilter> for OpenObserverTap {
    fn from(payload: ObserverFilter) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CloseObserverTap {
    pub fn new(payload: SubscriptionToken) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SubscriptionToken {
        &self.0
    }
    pub fn into_payload(self) -> SubscriptionToken {
        self.0
    }
}
#[rustfmt::skip]
impl From<SubscriptionToken> for CloseObserverTap {
    fn from(payload: SubscriptionToken) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Stashed {
    pub fn new(payload: StashResult) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &StashResult {
        &self.0
    }
    pub fn into_payload(self) -> StashResult {
        self.0
    }
}
#[rustfmt::skip]
impl From<StashResult> for Stashed {
    fn from(payload: StashResult) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl StateClassified {
    pub fn new(payload: Entry) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Entry {
        &self.0
    }
    pub fn into_payload(self) -> Entry {
        self.0
    }
}
#[rustfmt::skip]
impl From<Entry> for StateClassified {
    fn from(payload: Entry) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Recorded {
    pub fn new(payload: SemaReceipt) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SemaReceipt {
        &self.0
    }
    pub fn into_payload(self) -> SemaReceipt {
        self.0
    }
}
#[rustfmt::skip]
impl From<SemaReceipt> for Recorded {
    fn from(payload: SemaReceipt) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Proposed {
    pub fn new(payload: SemaReceipt) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SemaReceipt {
        &self.0
    }
    pub fn into_payload(self) -> SemaReceipt {
        self.0
    }
}
#[rustfmt::skip]
impl From<SemaReceipt> for Proposed {
    fn from(payload: SemaReceipt) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Clarified {
    pub fn new(payload: ClarificationReceipt) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ClarificationReceipt {
        &self.0
    }
    pub fn into_payload(self) -> ClarificationReceipt {
        self.0
    }
}
#[rustfmt::skip]
impl From<ClarificationReceipt> for Clarified {
    fn from(payload: ClarificationReceipt) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Superseded {
    pub fn new(payload: SupersessionReceipt) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SupersessionReceipt {
        &self.0
    }
    pub fn into_payload(self) -> SupersessionReceipt {
        self.0
    }
}
#[rustfmt::skip]
impl From<SupersessionReceipt> for Superseded {
    fn from(payload: SupersessionReceipt) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Retired {
    pub fn new(payload: RetirementReceipt) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RetirementReceipt {
        &self.0
    }
    pub fn into_payload(self) -> RetirementReceipt {
        self.0
    }
}
#[rustfmt::skip]
impl From<RetirementReceipt> for Retired {
    fn from(payload: RetirementReceipt) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl GuardianRejected {
    pub fn new(payload: GuardianRejection) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &GuardianRejection {
        &self.0
    }
    pub fn into_payload(self) -> GuardianRejection {
        self.0
    }
}
#[rustfmt::skip]
impl From<GuardianRejection> for GuardianRejected {
    fn from(payload: GuardianRejection) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl OperationFailed {
    pub fn new(payload: ErrorReport) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ErrorReport {
        &self.0
    }
    pub fn into_payload(self) -> ErrorReport {
        self.0
    }
}
#[rustfmt::skip]
impl From<ErrorReport> for OperationFailed {
    fn from(payload: ErrorReport) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl IntentSubscriptionOpened {
    pub fn new(payload: IntentSubscription) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &IntentSubscription {
        &self.0
    }
    pub fn into_payload(self) -> IntentSubscription {
        self.0
    }
}
#[rustfmt::skip]
impl From<IntentSubscription> for IntentSubscriptionOpened {
    fn from(payload: IntentSubscription) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RemovalCandidatesCollected {
    pub fn new(payload: RemovalCandidatesCollection) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RemovalCandidatesCollection {
        &self.0
    }
    pub fn into_payload(self) -> RemovalCandidatesCollection {
        self.0
    }
}
#[rustfmt::skip]
impl From<RemovalCandidatesCollection> for RemovalCandidatesCollected {
    fn from(payload: RemovalCandidatesCollection) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ObserverTapOpened {
    pub fn new(payload: ObserverSubscription) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ObserverSubscription {
        &self.0
    }
    pub fn into_payload(self) -> ObserverSubscription {
        self.0
    }
}
#[rustfmt::skip]
impl From<ObserverSubscription> for ObserverTapOpened {
    fn from(payload: ObserverSubscription) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ObserverTapClosed {
    pub fn new(payload: ObserverRetraction) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ObserverRetraction {
        &self.0
    }
    pub fn into_payload(self) -> ObserverRetraction {
        self.0
    }
}
#[rustfmt::skip]
impl From<ObserverRetraction> for ObserverTapClosed {
    fn from(payload: ObserverRetraction) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CommandSemaWrite {
    pub fn record(payload: Entry) -> Self {
        Self::Record(Record::new(payload))
    }
    pub fn remove(payload: RecordIdentifier) -> Self {
        Self::Remove(Remove::new(payload))
    }
    pub fn change_certainty(payload: CertaintyChange) -> Self {
        Self::ChangeCertainty(ChangeCertainty::new(payload))
    }
    pub fn bump_importance(payload: ImportanceBump) -> Self {
        Self::BumpImportance(BumpImportance::new(payload))
    }
    pub fn change_record(payload: RecordChange) -> Self {
        Self::ChangeRecord(ChangeRecord::new(payload))
    }
    pub fn register_referent(payload: ReferentRegistration) -> Self {
        Self::RegisterReferent(RegisterReferent::new(payload))
    }
}

#[rustfmt::skip]
impl NexusWork {
    pub fn signal_arrived(payload: SignalInput) -> Self {
        Self::SignalArrived(SignalArrived::new(payload))
    }
    pub fn sema_write_completed(payload: SemaWriteOutput) -> Self {
        Self::SemaWriteCompleted(SemaWriteCompleted::new(payload))
    }
    pub fn sema_read_completed(payload: SemaReadOutput) -> Self {
        Self::SemaReadCompleted(SemaReadCompleted::new(payload))
    }
    pub fn effect_completed(payload: NexusEffectResult) -> Self {
        Self::EffectCompleted(EffectCompleted::new(payload))
    }
}

#[rustfmt::skip]
impl NexusAction {
    pub fn command_sema_write(payload: CommandSemaWrite) -> Self {
        Self::CommandSemaWrite(payload)
    }
    pub fn command_sema_read(payload: SemaReadInput) -> Self {
        Self::CommandSemaRead(CommandSemaRead::new(payload))
    }
    pub fn reply_to_signal(payload: SignalOutput) -> Self {
        Self::ReplyToSignal(ReplyToSignal::new(payload))
    }
    pub fn command_effect(payload: NexusEffectCommand) -> Self {
        Self::CommandEffect(CommandEffect::new(payload))
    }
    pub fn r#continue(payload: NexusWork) -> Self {
        Self::Continue(Continue::new(payload))
    }
}

#[rustfmt::skip]
impl NexusEffectCommand {
    pub fn stash(payload: StashRequest) -> Self {
        Self::Stash(Stash::new(payload))
    }
    pub fn classify_state(payload: Statement) -> Self {
        Self::ClassifyState(ClassifyState::new(payload))
    }
    pub fn guard_record(payload: Entry) -> Self {
        Self::GuardRecord(GuardRecord::new(payload))
    }
    pub fn propose(payload: Entry) -> Self {
        Self::Propose(Propose::new(payload))
    }
    pub fn clarify(payload: Clarification) -> Self {
        Self::Clarify(Clarify::new(payload))
    }
    pub fn supersede(payload: Supersession) -> Self {
        Self::Supersede(Supersede::new(payload))
    }
    pub fn retire(payload: Retirement) -> Self {
        Self::Retire(Retire::new(payload))
    }
    pub fn open_intent_subscription(payload: Query) -> Self {
        Self::OpenIntentSubscription(OpenIntentSubscription::new(payload))
    }
    pub fn collect_removal_candidates(payload: RemovalCandidateCollection) -> Self {
        Self::CollectRemovalCandidates(CollectRemovalCandidates::new(payload))
    }
    pub fn open_observer_tap(payload: ObserverFilter) -> Self {
        Self::OpenObserverTap(OpenObserverTap::new(payload))
    }
    pub fn close_observer_tap(payload: SubscriptionToken) -> Self {
        Self::CloseObserverTap(CloseObserverTap::new(payload))
    }
}

#[rustfmt::skip]
impl NexusEffectResult {
    pub fn stashed(payload: StashResult) -> Self {
        Self::Stashed(Stashed::new(payload))
    }
    pub fn state_classified(payload: Entry) -> Self {
        Self::StateClassified(StateClassified::new(payload))
    }
    pub fn recorded(payload: SemaReceipt) -> Self {
        Self::Recorded(Recorded::new(payload))
    }
    pub fn proposed(payload: SemaReceipt) -> Self {
        Self::Proposed(Proposed::new(payload))
    }
    pub fn clarified(payload: ClarificationReceipt) -> Self {
        Self::Clarified(Clarified::new(payload))
    }
    pub fn superseded(payload: SupersessionReceipt) -> Self {
        Self::Superseded(Superseded::new(payload))
    }
    pub fn retired(payload: RetirementReceipt) -> Self {
        Self::Retired(Retired::new(payload))
    }
    pub fn guardian_rejected(payload: GuardianRejection) -> Self {
        Self::GuardianRejected(GuardianRejected::new(payload))
    }
    pub fn operation_failed(payload: ErrorReport) -> Self {
        Self::OperationFailed(OperationFailed::new(payload))
    }
    pub fn intent_subscription_opened(payload: IntentSubscription) -> Self {
        Self::IntentSubscriptionOpened(IntentSubscriptionOpened::new(payload))
    }
    pub fn removal_candidates_collected(payload: RemovalCandidatesCollection) -> Self {
        Self::RemovalCandidatesCollected(RemovalCandidatesCollected::new(payload))
    }
    pub fn observer_tap_opened(payload: ObserverSubscription) -> Self {
        Self::ObserverTapOpened(ObserverTapOpened::new(payload))
    }
    pub fn observer_tap_closed(payload: ObserverRetraction) -> Self {
        Self::ObserverTapClosed(ObserverTapClosed::new(payload))
    }
}

#[rustfmt::skip]
impl GuardianVerdict {
    pub fn reject(payload: Reject) -> Self {
        Self::Reject(payload)
    }
}

#[rustfmt::skip]
impl Input {
    pub fn signal_arrived(payload: SignalInput) -> Self {
        Self::SignalArrived(SignalArrived::new(payload))
    }
    pub fn sema_write_completed(payload: SemaWriteOutput) -> Self {
        Self::SemaWriteCompleted(SemaWriteCompleted::new(payload))
    }
    pub fn sema_read_completed(payload: SemaReadOutput) -> Self {
        Self::SemaReadCompleted(SemaReadCompleted::new(payload))
    }
    pub fn effect_completed(payload: NexusEffectResult) -> Self {
        Self::EffectCompleted(EffectCompleted::new(payload))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn command_sema_write(payload: CommandSemaWrite) -> Self {
        Self::CommandSemaWrite(payload)
    }
    pub fn command_sema_read(payload: SemaReadInput) -> Self {
        Self::CommandSemaRead(CommandSemaRead::new(payload))
    }
    pub fn reply_to_signal(payload: SignalOutput) -> Self {
        Self::ReplyToSignal(ReplyToSignal::new(payload))
    }
    pub fn command_effect(payload: NexusEffectCommand) -> Self {
        Self::CommandEffect(CommandEffect::new(payload))
    }
    pub fn r#continue(payload: NexusWork) -> Self {
        Self::Continue(Continue::new(payload))
    }
}

#[rustfmt::skip]
impl From<Record> for CommandSemaWrite {
    fn from(payload: Record) -> Self {
        Self::Record(payload)
    }
}

#[rustfmt::skip]
impl From<Remove> for CommandSemaWrite {
    fn from(payload: Remove) -> Self {
        Self::Remove(payload)
    }
}

#[rustfmt::skip]
impl From<ChangeCertainty> for CommandSemaWrite {
    fn from(payload: ChangeCertainty) -> Self {
        Self::ChangeCertainty(payload)
    }
}

#[rustfmt::skip]
impl From<BumpImportance> for CommandSemaWrite {
    fn from(payload: BumpImportance) -> Self {
        Self::BumpImportance(payload)
    }
}

#[rustfmt::skip]
impl From<ChangeRecord> for CommandSemaWrite {
    fn from(payload: ChangeRecord) -> Self {
        Self::ChangeRecord(payload)
    }
}

#[rustfmt::skip]
impl From<RegisterReferent> for CommandSemaWrite {
    fn from(payload: RegisterReferent) -> Self {
        Self::RegisterReferent(payload)
    }
}

#[rustfmt::skip]
impl From<SignalArrived> for NexusWork {
    fn from(payload: SignalArrived) -> Self {
        Self::SignalArrived(payload)
    }
}

#[rustfmt::skip]
impl From<SemaWriteCompleted> for NexusWork {
    fn from(payload: SemaWriteCompleted) -> Self {
        Self::SemaWriteCompleted(payload)
    }
}

#[rustfmt::skip]
impl From<SemaReadCompleted> for NexusWork {
    fn from(payload: SemaReadCompleted) -> Self {
        Self::SemaReadCompleted(payload)
    }
}

#[rustfmt::skip]
impl From<EffectCompleted> for NexusWork {
    fn from(payload: EffectCompleted) -> Self {
        Self::EffectCompleted(payload)
    }
}

#[rustfmt::skip]
impl From<CommandSemaWrite> for NexusAction {
    fn from(payload: CommandSemaWrite) -> Self {
        Self::CommandSemaWrite(payload)
    }
}

#[rustfmt::skip]
impl From<CommandSemaRead> for NexusAction {
    fn from(payload: CommandSemaRead) -> Self {
        Self::CommandSemaRead(payload)
    }
}

#[rustfmt::skip]
impl From<ReplyToSignal> for NexusAction {
    fn from(payload: ReplyToSignal) -> Self {
        Self::ReplyToSignal(payload)
    }
}

#[rustfmt::skip]
impl From<CommandEffect> for NexusAction {
    fn from(payload: CommandEffect) -> Self {
        Self::CommandEffect(payload)
    }
}

#[rustfmt::skip]
impl From<Continue> for NexusAction {
    fn from(payload: Continue) -> Self {
        Self::Continue(payload)
    }
}

#[rustfmt::skip]
impl From<Stash> for NexusEffectCommand {
    fn from(payload: Stash) -> Self {
        Self::Stash(payload)
    }
}

#[rustfmt::skip]
impl From<ClassifyState> for NexusEffectCommand {
    fn from(payload: ClassifyState) -> Self {
        Self::ClassifyState(payload)
    }
}

#[rustfmt::skip]
impl From<GuardRecord> for NexusEffectCommand {
    fn from(payload: GuardRecord) -> Self {
        Self::GuardRecord(payload)
    }
}

#[rustfmt::skip]
impl From<Propose> for NexusEffectCommand {
    fn from(payload: Propose) -> Self {
        Self::Propose(payload)
    }
}

#[rustfmt::skip]
impl From<Clarify> for NexusEffectCommand {
    fn from(payload: Clarify) -> Self {
        Self::Clarify(payload)
    }
}

#[rustfmt::skip]
impl From<Supersede> for NexusEffectCommand {
    fn from(payload: Supersede) -> Self {
        Self::Supersede(payload)
    }
}

#[rustfmt::skip]
impl From<Retire> for NexusEffectCommand {
    fn from(payload: Retire) -> Self {
        Self::Retire(payload)
    }
}

#[rustfmt::skip]
impl From<OpenIntentSubscription> for NexusEffectCommand {
    fn from(payload: OpenIntentSubscription) -> Self {
        Self::OpenIntentSubscription(payload)
    }
}

#[rustfmt::skip]
impl From<CollectRemovalCandidates> for NexusEffectCommand {
    fn from(payload: CollectRemovalCandidates) -> Self {
        Self::CollectRemovalCandidates(payload)
    }
}

#[rustfmt::skip]
impl From<OpenObserverTap> for NexusEffectCommand {
    fn from(payload: OpenObserverTap) -> Self {
        Self::OpenObserverTap(payload)
    }
}

#[rustfmt::skip]
impl From<CloseObserverTap> for NexusEffectCommand {
    fn from(payload: CloseObserverTap) -> Self {
        Self::CloseObserverTap(payload)
    }
}

#[rustfmt::skip]
impl From<Stashed> for NexusEffectResult {
    fn from(payload: Stashed) -> Self {
        Self::Stashed(payload)
    }
}

#[rustfmt::skip]
impl From<StateClassified> for NexusEffectResult {
    fn from(payload: StateClassified) -> Self {
        Self::StateClassified(payload)
    }
}

#[rustfmt::skip]
impl From<Recorded> for NexusEffectResult {
    fn from(payload: Recorded) -> Self {
        Self::Recorded(payload)
    }
}

#[rustfmt::skip]
impl From<Proposed> for NexusEffectResult {
    fn from(payload: Proposed) -> Self {
        Self::Proposed(payload)
    }
}

#[rustfmt::skip]
impl From<Clarified> for NexusEffectResult {
    fn from(payload: Clarified) -> Self {
        Self::Clarified(payload)
    }
}

#[rustfmt::skip]
impl From<Superseded> for NexusEffectResult {
    fn from(payload: Superseded) -> Self {
        Self::Superseded(payload)
    }
}

#[rustfmt::skip]
impl From<Retired> for NexusEffectResult {
    fn from(payload: Retired) -> Self {
        Self::Retired(payload)
    }
}

#[rustfmt::skip]
impl From<GuardianRejected> for NexusEffectResult {
    fn from(payload: GuardianRejected) -> Self {
        Self::GuardianRejected(payload)
    }
}

#[rustfmt::skip]
impl From<OperationFailed> for NexusEffectResult {
    fn from(payload: OperationFailed) -> Self {
        Self::OperationFailed(payload)
    }
}

#[rustfmt::skip]
impl From<IntentSubscriptionOpened> for NexusEffectResult {
    fn from(payload: IntentSubscriptionOpened) -> Self {
        Self::IntentSubscriptionOpened(payload)
    }
}

#[rustfmt::skip]
impl From<RemovalCandidatesCollected> for NexusEffectResult {
    fn from(payload: RemovalCandidatesCollected) -> Self {
        Self::RemovalCandidatesCollected(payload)
    }
}

#[rustfmt::skip]
impl From<ObserverTapOpened> for NexusEffectResult {
    fn from(payload: ObserverTapOpened) -> Self {
        Self::ObserverTapOpened(payload)
    }
}

#[rustfmt::skip]
impl From<ObserverTapClosed> for NexusEffectResult {
    fn from(payload: ObserverTapClosed) -> Self {
        Self::ObserverTapClosed(payload)
    }
}

#[rustfmt::skip]
impl From<Reject> for GuardianVerdict {
    fn from(payload: Reject) -> Self {
        Self::Reject(payload)
    }
}

#[rustfmt::skip]
impl From<SignalArrived> for Input {
    fn from(payload: SignalArrived) -> Self {
        Self::SignalArrived(payload)
    }
}

#[rustfmt::skip]
impl From<SemaWriteCompleted> for Input {
    fn from(payload: SemaWriteCompleted) -> Self {
        Self::SemaWriteCompleted(payload)
    }
}

#[rustfmt::skip]
impl From<SemaReadCompleted> for Input {
    fn from(payload: SemaReadCompleted) -> Self {
        Self::SemaReadCompleted(payload)
    }
}

#[rustfmt::skip]
impl From<EffectCompleted> for Input {
    fn from(payload: EffectCompleted) -> Self {
        Self::EffectCompleted(payload)
    }
}

#[rustfmt::skip]
impl From<CommandSemaWrite> for Output {
    fn from(payload: CommandSemaWrite) -> Self {
        Self::CommandSemaWrite(payload)
    }
}

#[rustfmt::skip]
impl From<CommandSemaRead> for Output {
    fn from(payload: CommandSemaRead) -> Self {
        Self::CommandSemaRead(payload)
    }
}

#[rustfmt::skip]
impl From<ReplyToSignal> for Output {
    fn from(payload: ReplyToSignal) -> Self {
        Self::ReplyToSignal(payload)
    }
}

#[rustfmt::skip]
impl From<CommandEffect> for Output {
    fn from(payload: CommandEffect) -> Self {
        Self::CommandEffect(payload)
    }
}

#[rustfmt::skip]
impl From<Continue> for Output {
    fn from(payload: Continue) -> Self {
        Self::Continue(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl SignalArrived {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl SemaWriteCompleted {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl SemaReadCompleted {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl EffectCompleted {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl CommandSemaWrite {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Record {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Remove {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ChangeCertainty {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl BumpImportance {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ChangeRecord {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl RegisterReferent {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl CommandSemaRead {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ReplyToSignal {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl CommandEffect {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Continue {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl NexusWork {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl NexusAction {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl NexusEffectCommand {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Stash {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ClassifyState {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl GuardRecord {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Propose {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Clarify {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Supersede {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Retire {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl OpenIntentSubscription {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl CollectRemovalCandidates {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl OpenObserverTap {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl CloseObserverTap {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl NexusEffectResult {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Stashed {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl StateClassified {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Recorded {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Proposed {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Clarified {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Superseded {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Retired {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl GuardianRejected {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl OperationFailed {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl IntentSubscriptionOpened {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl RemovalCandidatesCollected {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ObserverTapOpened {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ObserverTapClosed {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl StashRequest {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl StashResult {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl GuardianVerdict {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Reject {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Input {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Output {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum NexusWorkRoute {
    SignalArrived,
    SemaWriteCompleted,
    SemaReadCompleted,
    EffectCompleted,
}

#[rustfmt::skip]
impl NexusWork {
    pub fn route(&self) -> NexusWorkRoute {
        match self {
            Self::SignalArrived(_) => NexusWorkRoute::SignalArrived,
            Self::SemaWriteCompleted(_) => NexusWorkRoute::SemaWriteCompleted,
            Self::SemaReadCompleted(_) => NexusWorkRoute::SemaReadCompleted,
            Self::EffectCompleted(_) => NexusWorkRoute::EffectCompleted,
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum NexusActionRoute {
    CommandSemaWrite,
    CommandSemaRead,
    ReplyToSignal,
    CommandEffect,
    Continue,
}

#[rustfmt::skip]
impl NexusAction {
    pub fn route(&self) -> NexusActionRoute {
        match self {
            Self::CommandSemaWrite(_) => NexusActionRoute::CommandSemaWrite,
            Self::CommandSemaRead(_) => NexusActionRoute::CommandSemaRead,
            Self::ReplyToSignal(_) => NexusActionRoute::ReplyToSignal,
            Self::CommandEffect(_) => NexusActionRoute::CommandEffect,
            Self::Continue(_) => NexusActionRoute::Continue,
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum NexusObjectName {
    Work(NexusWorkRoute),
    Action(NexusActionRoute),
    Started,
    Stopped,
    Entered,
    Decided,
}
#[rustfmt::skip]
impl NexusObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::Work(route) => {
                match route {
                    NexusWorkRoute::SignalArrived => "NexusWorkSignalArrived",
                    NexusWorkRoute::SemaWriteCompleted => "NexusWorkSemaWriteCompleted",
                    NexusWorkRoute::SemaReadCompleted => "NexusWorkSemaReadCompleted",
                    NexusWorkRoute::EffectCompleted => "NexusWorkEffectCompleted",
                }
            }
            Self::Action(route) => {
                match route {
                    NexusActionRoute::CommandSemaWrite => "NexusActionCommandSemaWrite",
                    NexusActionRoute::CommandSemaRead => "NexusActionCommandSemaRead",
                    NexusActionRoute::ReplyToSignal => "NexusActionReplyToSignal",
                    NexusActionRoute::CommandEffect => "NexusActionCommandEffect",
                    NexusActionRoute::Continue => "NexusActionContinue",
                }
            }
            Self::Started => "NexusStarted",
            Self::Stopped => "NexusStopped",
            Self::Entered => "NexusEntered",
            Self::Decided => "NexusDecided",
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ObjectName {
    Nexus(NexusObjectName),
}
#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct TraceEvent(pub ObjectName);
#[rustfmt::skip]
impl ObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::Nexus(object_name) => object_name.name(),
        }
    }
}
#[rustfmt::skip]
impl TraceEvent {
    pub fn new(object_name: ObjectName) -> Self {
        Self(object_name)
    }
    pub fn object_name(&self) -> ObjectName {
        self.0
    }
    pub fn name(&self) -> &'static str {
        self.0.name()
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct OriginRoute(Integer);
#[rustfmt::skip]
impl OriginRoute {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl OriginRoute {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(self) -> String {
        <Self as NotaEncode>::to_nota(&self)
    }
}

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Nexus<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}
#[rustfmt::skip]
impl<Root> Nexus<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }
    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }
    pub fn root(&self) -> &Root {
        &self.root
    }
    pub fn into_root(self) -> Root {
        self.root
    }
    pub fn map_root<NextRoot>(
        self,
        map: impl FnOnce(Root) -> NextRoot,
    ) -> Nexus<NextRoot> {
        Nexus::new(self.origin_route, map(self.root))
    }
}

#[rustfmt::skip]
#[allow(clippy::module_inception)]
pub mod nexus {
    pub type Work = super::NexusWork;
    pub type Action = super::NexusAction;
    pub type Nexus<Root> = super::Nexus<Root>;
}

#[rustfmt::skip]
impl NexusWork {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> nexus::Nexus<Self> {
        nexus::Nexus::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl NexusAction {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> nexus::Nexus<Self> {
        nexus::Nexus::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl triad_runtime::NexusWork for NexusWork {}

#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum EngineStartFailure {
    ResourceBusy(String),
    ConfigurationInvalid(String),
}
#[rustfmt::skip]
impl std::fmt::Display for EngineStartFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceBusy(message) => {
                write!(formatter, "engine resource busy: {message}")
            }
            Self::ConfigurationInvalid(message) => {
                write!(formatter, "engine configuration invalid: {message}")
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for EngineStartFailure {}
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum EngineStopFailure {
    ResourceLocked(String),
    ChildStillRunning(String),
}
#[rustfmt::skip]
impl std::fmt::Display for EngineStopFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceLocked(message) => {
                write!(formatter, "engine resource locked: {message}")
            }
            Self::ChildStillRunning(message) => {
                write!(formatter, "engine child still running: {message}")
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for EngineStopFailure {}

#[rustfmt::skip]
pub trait NexusEngine: Send {
    fn on_start(&mut self) -> Result<(), EngineStartFailure> {
        Ok(())
    }
    fn on_stop(&mut self) -> Result<(), EngineStopFailure> {
        Ok(())
    }
    fn trace_nexus_activation(&self, _object_name: NexusObjectName) {}
    fn trace_nexus_entered(&self) {
        self.trace_nexus_activation(NexusObjectName::Entered);
    }
    fn trace_nexus_decided(&self) {
        self.trace_nexus_activation(NexusObjectName::Decided);
    }
    fn decide(
        &mut self,
        input: nexus::Nexus<nexus::Work>,
    ) -> nexus::Nexus<nexus::Action>;
    fn execute(
        &mut self,
        input: nexus::Nexus<nexus::Work>,
    ) -> impl std::future::Future<Output = nexus::Nexus<nexus::Action>> + Send + '_ {
        async move {
            self.trace_nexus_entered();
            let output = self.decide(input);
            self.trace_nexus_decided();
            output
        }
    }
}

#[rustfmt::skip]
pub trait UpgradeFrom<Previous>: Sized {
    type Error;
    fn upgrade_from(previous: Previous) -> Result<Self, Self::Error>;
}
#[rustfmt::skip]
pub trait AcceptPrevious<Previous>: UpgradeFrom<Previous> {
    fn accept_previous(previous: Previous) -> Result<Self, Self::Error> {
        Self::upgrade_from(previous)
    }
}
#[rustfmt::skip]
impl<Current, Previous> AcceptPrevious<Previous> for Current
where
    Current: UpgradeFrom<Previous>,
{}
