// @generated by schema-rust-next

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
pub use signal_spirit::schema::signal::Entry as Entry;
#[rustfmt::skip]
pub use signal_spirit::schema::signal::Query as Query;
#[rustfmt::skip]
pub use signal_spirit::schema::signal::RecordIdentifier as RecordIdentifier;
#[rustfmt::skip]
pub use signal_spirit::schema::signal::Referent as Referent;
#[rustfmt::skip]
pub use signal_spirit::schema::signal::Referents as Referents;
#[rustfmt::skip]
pub use signal_spirit::schema::signal::SearchText as SearchText;
#[rustfmt::skip]
pub use signal_spirit::schema::signal::Removal as Removal;
#[rustfmt::skip]
pub use signal_spirit::schema::signal::CertaintyChange as CertaintyChange;
#[rustfmt::skip]
pub use signal_spirit::schema::signal::ImportanceBump as ImportanceBump;
#[rustfmt::skip]
pub use signal_spirit::schema::signal::RecordChange as RecordChange;
#[rustfmt::skip]
pub use signal_spirit::schema::signal::ReferentRegistration as ReferentRegistration;
#[rustfmt::skip]
pub use signal_spirit::schema::signal::SemaReceipt as SemaReceipt;
#[rustfmt::skip]
pub use signal_spirit::schema::signal::RemoveReceipt as RemoveReceipt;
#[rustfmt::skip]
pub use signal_spirit::schema::signal::CertaintyChangeReceipt as CertaintyChangeReceipt;
#[rustfmt::skip]
pub use signal_spirit::schema::signal::ImportanceBumpReceipt as ImportanceBumpReceipt;
#[rustfmt::skip]
pub use signal_spirit::schema::signal::RecordChangeReceipt as RecordChangeReceipt;
#[rustfmt::skip]
pub use signal_spirit::schema::signal::ReferentRegistrationReceipt as ReferentRegistrationReceipt;
#[rustfmt::skip]
pub use signal_spirit::schema::signal::ObservedRecords as ObservedRecords;
#[rustfmt::skip]
pub use signal_spirit::schema::signal::FoundRecord as FoundRecord;
#[rustfmt::skip]
pub use signal_spirit::schema::signal::CountedRecords as CountedRecords;
#[rustfmt::skip]
pub use signal_spirit::schema::signal::ErrorReport as ErrorReport;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota_next::{NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum WriteInput {
    Record(Record),
    Remove(Remove),
    ChangeCertainty(ChangeCertainty),
    BumpImportance(BumpImportance),
    ChangeRecord(ChangeRecord),
    RegisterReferent(RegisterReferent),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Record(Entry);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Remove(Removal);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ChangeCertainty(CertaintyChange);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct BumpImportance(ImportanceBump);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ChangeRecord(RecordChange);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RegisterReferent(ReferentRegistration);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ReadInput {
    Observe(Observe),
    PublicTextSearch(PublicTextSearch),
    Lookup(Lookup),
    Count(Count),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Observe(Query);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PublicTextSearch(SearchText);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Lookup(RecordIdentifier);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Count(Query);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum WriteOutput {
    Recorded(Recorded),
    Removed(Removed),
    CertaintyChanged(CertaintyChanged),
    ImportanceBumped(ImportanceBumped),
    RecordChanged(RecordChanged),
    ReferentRegistered(ReferentRegistered),
    Missed(Missed),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Recorded(SemaReceipt);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Removed(RemoveReceipt);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CertaintyChanged(CertaintyChangeReceipt);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ImportanceBumped(ImportanceBumpReceipt);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RecordChanged(RecordChangeReceipt);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ReferentRegistered(ReferentRegistrationReceipt);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Missed(ErrorReport);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ReadOutput {
    Observed(Observed),
    PublicTextSearchResults(PublicTextSearchResults),
    Found(Found),
    Counted(Counted),
    Missed(Missed),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Observed(ObservedRecords);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PublicTextSearchResults(ObservedRecords);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Found(FoundRecord);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Counted(CountedRecords);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StoredRecord {
    pub record_identifier: RecordIdentifier,
    pub entry: Entry,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StoredReferent {
    pub referent: Referent,
    pub aliases: Referents,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SourceSchemaVersion(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MigratedRecordCount(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MigratedReferentCount(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Migration {
    pub source_schema_version: SourceSchemaVersion,
    pub migrated_record_count: MigratedRecordCount,
    pub migrated_referent_count: MigratedReferentCount,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    WriteInput(WriteInput),
    ReadInput(ReadInput),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    WriteOutput(WriteOutput),
    ReadOutput(ReadOutput),
}

#[rustfmt::skip]
impl Record {
    pub fn new(payload: Entry) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Entry {
        &self.0
    }
    pub fn into_payload(self) -> Entry {
        self.0
    }
}
#[rustfmt::skip]
impl From<Entry> for Record {
    fn from(payload: Entry) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Remove {
    pub fn new(payload: Removal) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Removal {
        &self.0
    }
    pub fn into_payload(self) -> Removal {
        self.0
    }
}
#[rustfmt::skip]
impl From<Removal> for Remove {
    fn from(payload: Removal) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ChangeCertainty {
    pub fn new(payload: CertaintyChange) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &CertaintyChange {
        &self.0
    }
    pub fn into_payload(self) -> CertaintyChange {
        self.0
    }
}
#[rustfmt::skip]
impl From<CertaintyChange> for ChangeCertainty {
    fn from(payload: CertaintyChange) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl BumpImportance {
    pub fn new(payload: ImportanceBump) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ImportanceBump {
        &self.0
    }
    pub fn into_payload(self) -> ImportanceBump {
        self.0
    }
}
#[rustfmt::skip]
impl From<ImportanceBump> for BumpImportance {
    fn from(payload: ImportanceBump) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ChangeRecord {
    pub fn new(payload: RecordChange) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RecordChange {
        &self.0
    }
    pub fn into_payload(self) -> RecordChange {
        self.0
    }
}
#[rustfmt::skip]
impl From<RecordChange> for ChangeRecord {
    fn from(payload: RecordChange) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RegisterReferent {
    pub fn new(payload: ReferentRegistration) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ReferentRegistration {
        &self.0
    }
    pub fn into_payload(self) -> ReferentRegistration {
        self.0
    }
}
#[rustfmt::skip]
impl From<ReferentRegistration> for RegisterReferent {
    fn from(payload: ReferentRegistration) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Observe {
    pub fn new(payload: Query) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Query {
        &self.0
    }
    pub fn into_payload(self) -> Query {
        self.0
    }
}
#[rustfmt::skip]
impl From<Query> for Observe {
    fn from(payload: Query) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl PublicTextSearch {
    pub fn new(payload: SearchText) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SearchText {
        &self.0
    }
    pub fn into_payload(self) -> SearchText {
        self.0
    }
}
#[rustfmt::skip]
impl From<SearchText> for PublicTextSearch {
    fn from(payload: SearchText) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Lookup {
    pub fn new(payload: RecordIdentifier) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RecordIdentifier {
        &self.0
    }
    pub fn into_payload(self) -> RecordIdentifier {
        self.0
    }
}
#[rustfmt::skip]
impl From<RecordIdentifier> for Lookup {
    fn from(payload: RecordIdentifier) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Count {
    pub fn new(payload: Query) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Query {
        &self.0
    }
    pub fn into_payload(self) -> Query {
        self.0
    }
}
#[rustfmt::skip]
impl From<Query> for Count {
    fn from(payload: Query) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Recorded {
    pub fn new(payload: SemaReceipt) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SemaReceipt {
        &self.0
    }
    pub fn into_payload(self) -> SemaReceipt {
        self.0
    }
}
#[rustfmt::skip]
impl From<SemaReceipt> for Recorded {
    fn from(payload: SemaReceipt) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Removed {
    pub fn new(payload: RemoveReceipt) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RemoveReceipt {
        &self.0
    }
    pub fn into_payload(self) -> RemoveReceipt {
        self.0
    }
}
#[rustfmt::skip]
impl From<RemoveReceipt> for Removed {
    fn from(payload: RemoveReceipt) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CertaintyChanged {
    pub fn new(payload: CertaintyChangeReceipt) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &CertaintyChangeReceipt {
        &self.0
    }
    pub fn into_payload(self) -> CertaintyChangeReceipt {
        self.0
    }
}
#[rustfmt::skip]
impl From<CertaintyChangeReceipt> for CertaintyChanged {
    fn from(payload: CertaintyChangeReceipt) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ImportanceBumped {
    pub fn new(payload: ImportanceBumpReceipt) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ImportanceBumpReceipt {
        &self.0
    }
    pub fn into_payload(self) -> ImportanceBumpReceipt {
        self.0
    }
}
#[rustfmt::skip]
impl From<ImportanceBumpReceipt> for ImportanceBumped {
    fn from(payload: ImportanceBumpReceipt) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RecordChanged {
    pub fn new(payload: RecordChangeReceipt) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RecordChangeReceipt {
        &self.0
    }
    pub fn into_payload(self) -> RecordChangeReceipt {
        self.0
    }
}
#[rustfmt::skip]
impl From<RecordChangeReceipt> for RecordChanged {
    fn from(payload: RecordChangeReceipt) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ReferentRegistered {
    pub fn new(payload: ReferentRegistrationReceipt) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ReferentRegistrationReceipt {
        &self.0
    }
    pub fn into_payload(self) -> ReferentRegistrationReceipt {
        self.0
    }
}
#[rustfmt::skip]
impl From<ReferentRegistrationReceipt> for ReferentRegistered {
    fn from(payload: ReferentRegistrationReceipt) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Missed {
    pub fn new(payload: ErrorReport) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ErrorReport {
        &self.0
    }
    pub fn into_payload(self) -> ErrorReport {
        self.0
    }
}
#[rustfmt::skip]
impl From<ErrorReport> for Missed {
    fn from(payload: ErrorReport) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Observed {
    pub fn new(payload: ObservedRecords) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ObservedRecords {
        &self.0
    }
    pub fn into_payload(self) -> ObservedRecords {
        self.0
    }
}
#[rustfmt::skip]
impl From<ObservedRecords> for Observed {
    fn from(payload: ObservedRecords) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl PublicTextSearchResults {
    pub fn new(payload: ObservedRecords) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ObservedRecords {
        &self.0
    }
    pub fn into_payload(self) -> ObservedRecords {
        self.0
    }
}
#[rustfmt::skip]
impl From<ObservedRecords> for PublicTextSearchResults {
    fn from(payload: ObservedRecords) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Found {
    pub fn new(payload: FoundRecord) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &FoundRecord {
        &self.0
    }
    pub fn into_payload(self) -> FoundRecord {
        self.0
    }
}
#[rustfmt::skip]
impl From<FoundRecord> for Found {
    fn from(payload: FoundRecord) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Counted {
    pub fn new(payload: CountedRecords) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &CountedRecords {
        &self.0
    }
    pub fn into_payload(self) -> CountedRecords {
        self.0
    }
}
#[rustfmt::skip]
impl From<CountedRecords> for Counted {
    fn from(payload: CountedRecords) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SourceSchemaVersion {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for SourceSchemaVersion {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl MigratedRecordCount {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for MigratedRecordCount {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl MigratedReferentCount {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for MigratedReferentCount {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl WriteInput {
    pub fn record(payload: Entry) -> Self {
        Self::Record(Record::new(payload))
    }
    pub fn remove(payload: Removal) -> Self {
        Self::Remove(Remove::new(payload))
    }
    pub fn change_certainty(payload: CertaintyChange) -> Self {
        Self::ChangeCertainty(ChangeCertainty::new(payload))
    }
    pub fn bump_importance(payload: ImportanceBump) -> Self {
        Self::BumpImportance(BumpImportance::new(payload))
    }
    pub fn change_record(payload: RecordChange) -> Self {
        Self::ChangeRecord(ChangeRecord::new(payload))
    }
    pub fn register_referent(payload: ReferentRegistration) -> Self {
        Self::RegisterReferent(RegisterReferent::new(payload))
    }
}

#[rustfmt::skip]
impl ReadInput {
    pub fn observe(payload: Query) -> Self {
        Self::Observe(Observe::new(payload))
    }
    pub fn public_text_search(payload: SearchText) -> Self {
        Self::PublicTextSearch(PublicTextSearch::new(payload))
    }
    pub fn lookup(payload: RecordIdentifier) -> Self {
        Self::Lookup(Lookup::new(payload))
    }
    pub fn count(payload: Query) -> Self {
        Self::Count(Count::new(payload))
    }
}

#[rustfmt::skip]
impl WriteOutput {
    pub fn recorded(payload: SemaReceipt) -> Self {
        Self::Recorded(Recorded::new(payload))
    }
    pub fn removed(payload: RemoveReceipt) -> Self {
        Self::Removed(Removed::new(payload))
    }
    pub fn certainty_changed(payload: CertaintyChangeReceipt) -> Self {
        Self::CertaintyChanged(CertaintyChanged::new(payload))
    }
    pub fn importance_bumped(payload: ImportanceBumpReceipt) -> Self {
        Self::ImportanceBumped(ImportanceBumped::new(payload))
    }
    pub fn record_changed(payload: RecordChangeReceipt) -> Self {
        Self::RecordChanged(RecordChanged::new(payload))
    }
    pub fn referent_registered(payload: ReferentRegistrationReceipt) -> Self {
        Self::ReferentRegistered(ReferentRegistered::new(payload))
    }
    pub fn missed(payload: ErrorReport) -> Self {
        Self::Missed(Missed::new(payload))
    }
}

#[rustfmt::skip]
impl ReadOutput {
    pub fn observed(payload: ObservedRecords) -> Self {
        Self::Observed(Observed::new(payload))
    }
    pub fn public_text_search_results(payload: ObservedRecords) -> Self {
        Self::PublicTextSearchResults(PublicTextSearchResults::new(payload))
    }
    pub fn found(payload: FoundRecord) -> Self {
        Self::Found(Found::new(payload))
    }
    pub fn counted(payload: CountedRecords) -> Self {
        Self::Counted(Counted::new(payload))
    }
    pub fn missed(payload: ErrorReport) -> Self {
        Self::Missed(Missed::new(payload))
    }
}

#[rustfmt::skip]
impl Input {
    pub fn write_input(payload: WriteInput) -> Self {
        Self::WriteInput(payload)
    }
    pub fn read_input(payload: ReadInput) -> Self {
        Self::ReadInput(payload)
    }
}

#[rustfmt::skip]
impl Output {
    pub fn write_output(payload: WriteOutput) -> Self {
        Self::WriteOutput(payload)
    }
    pub fn read_output(payload: ReadOutput) -> Self {
        Self::ReadOutput(payload)
    }
}

#[rustfmt::skip]
impl From<Record> for WriteInput {
    fn from(payload: Record) -> Self {
        Self::Record(payload)
    }
}

#[rustfmt::skip]
impl From<Remove> for WriteInput {
    fn from(payload: Remove) -> Self {
        Self::Remove(payload)
    }
}

#[rustfmt::skip]
impl From<ChangeCertainty> for WriteInput {
    fn from(payload: ChangeCertainty) -> Self {
        Self::ChangeCertainty(payload)
    }
}

#[rustfmt::skip]
impl From<BumpImportance> for WriteInput {
    fn from(payload: BumpImportance) -> Self {
        Self::BumpImportance(payload)
    }
}

#[rustfmt::skip]
impl From<ChangeRecord> for WriteInput {
    fn from(payload: ChangeRecord) -> Self {
        Self::ChangeRecord(payload)
    }
}

#[rustfmt::skip]
impl From<RegisterReferent> for WriteInput {
    fn from(payload: RegisterReferent) -> Self {
        Self::RegisterReferent(payload)
    }
}

#[rustfmt::skip]
impl From<Observe> for ReadInput {
    fn from(payload: Observe) -> Self {
        Self::Observe(payload)
    }
}

#[rustfmt::skip]
impl From<PublicTextSearch> for ReadInput {
    fn from(payload: PublicTextSearch) -> Self {
        Self::PublicTextSearch(payload)
    }
}

#[rustfmt::skip]
impl From<Lookup> for ReadInput {
    fn from(payload: Lookup) -> Self {
        Self::Lookup(payload)
    }
}

#[rustfmt::skip]
impl From<Count> for ReadInput {
    fn from(payload: Count) -> Self {
        Self::Count(payload)
    }
}

#[rustfmt::skip]
impl From<Recorded> for WriteOutput {
    fn from(payload: Recorded) -> Self {
        Self::Recorded(payload)
    }
}

#[rustfmt::skip]
impl From<Removed> for WriteOutput {
    fn from(payload: Removed) -> Self {
        Self::Removed(payload)
    }
}

#[rustfmt::skip]
impl From<CertaintyChanged> for WriteOutput {
    fn from(payload: CertaintyChanged) -> Self {
        Self::CertaintyChanged(payload)
    }
}

#[rustfmt::skip]
impl From<ImportanceBumped> for WriteOutput {
    fn from(payload: ImportanceBumped) -> Self {
        Self::ImportanceBumped(payload)
    }
}

#[rustfmt::skip]
impl From<RecordChanged> for WriteOutput {
    fn from(payload: RecordChanged) -> Self {
        Self::RecordChanged(payload)
    }
}

#[rustfmt::skip]
impl From<ReferentRegistered> for WriteOutput {
    fn from(payload: ReferentRegistered) -> Self {
        Self::ReferentRegistered(payload)
    }
}

#[rustfmt::skip]
impl From<Missed> for WriteOutput {
    fn from(payload: Missed) -> Self {
        Self::Missed(payload)
    }
}

#[rustfmt::skip]
impl From<Observed> for ReadOutput {
    fn from(payload: Observed) -> Self {
        Self::Observed(payload)
    }
}

#[rustfmt::skip]
impl From<PublicTextSearchResults> for ReadOutput {
    fn from(payload: PublicTextSearchResults) -> Self {
        Self::PublicTextSearchResults(payload)
    }
}

#[rustfmt::skip]
impl From<Found> for ReadOutput {
    fn from(payload: Found) -> Self {
        Self::Found(payload)
    }
}

#[rustfmt::skip]
impl From<Counted> for ReadOutput {
    fn from(payload: Counted) -> Self {
        Self::Counted(payload)
    }
}

#[rustfmt::skip]
impl From<Missed> for ReadOutput {
    fn from(payload: Missed) -> Self {
        Self::Missed(payload)
    }
}

#[rustfmt::skip]
impl From<WriteInput> for Input {
    fn from(payload: WriteInput) -> Self {
        Self::WriteInput(payload)
    }
}

#[rustfmt::skip]
impl From<ReadInput> for Input {
    fn from(payload: ReadInput) -> Self {
        Self::ReadInput(payload)
    }
}

#[rustfmt::skip]
impl From<WriteOutput> for Output {
    fn from(payload: WriteOutput) -> Self {
        Self::WriteOutput(payload)
    }
}

#[rustfmt::skip]
impl From<ReadOutput> for Output {
    fn from(payload: ReadOutput) -> Self {
        Self::ReadOutput(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
pub mod family_identity {
    pub const RECORDS_FAMILY: [u8; 32] = [
        219, 229, 55, 148, 22, 84, 6, 238, 209, 54, 85, 8, 143, 71, 138, 253, 217, 104,
        214, 226, 42, 107, 225, 10, 84, 55, 112, 66, 235, 33, 159, 8,
    ];
    pub const REFERENTS_FAMILY: [u8; 32] = [
        188, 175, 255, 243, 118, 25, 152, 34, 112, 24, 219, 110, 187, 78, 78, 34, 118,
        22, 115, 224, 202, 82, 84, 91, 187, 206, 22, 170, 72, 207, 109, 223,
    ];
    pub const MIGRATIONS_FAMILY: [u8; 32] = [
        206, 173, 177, 83, 157, 76, 146, 116, 73, 239, 9, 84, 47, 56, 124, 17, 182, 138,
        11, 62, 87, 91, 128, 182, 153, 147, 110, 148, 96, 134, 152, 154,
    ];
}

#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum RecordFamilyError {
    UnknownFamily { family: sema_engine::FamilyName },
    SchemaHashMismatch {
        family: sema_engine::FamilyName,
        stored: sema_engine::SchemaHash,
        generated: sema_engine::SchemaHash,
    },
    RecordDecode { family: sema_engine::FamilyName },
}
#[rustfmt::skip]
impl std::fmt::Display for RecordFamilyError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::UnknownFamily { family } => {
                write!(formatter, "unknown record family {family}")
            }
            Self::SchemaHashMismatch { family, stored, generated } => {
                write!(
                    formatter,
                    "schema hash mismatch for record family {family}: stored {stored}, generated {generated}",
                )
            }
            Self::RecordDecode { family } => {
                write!(formatter, "failed to decode {family} record archive")
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for RecordFamilyError {}

#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq)]
pub enum RecordFamily {
    RecordsFamily(StoredRecord),
    ReferentsFamily(StoredReferent),
    MigrationsFamily(Migration),
}
#[rustfmt::skip]
impl RecordFamily {
    pub const STORE_NAME: &'static str = "spirit:sema";
    pub fn versioning_policy() -> sema_engine::VersioningPolicy {
        sema_engine::VersioningPolicy::new(
            sema_engine::VersionedStoreName::new(Self::STORE_NAME),
        )
    }
    pub fn records_family() -> sema_engine::TableDescriptor<StoredRecord> {
        sema_engine::TableDescriptor::new(
            sema_engine::TableName::new("records"),
            sema_engine::FamilyName::new("RecordsFamily"),
            sema_engine::SchemaHash::new(family_identity::RECORDS_FAMILY),
        )
    }
    pub fn referents_family() -> sema_engine::TableDescriptor<StoredReferent> {
        sema_engine::TableDescriptor::new(
            sema_engine::TableName::new("referents"),
            sema_engine::FamilyName::new("ReferentsFamily"),
            sema_engine::SchemaHash::new(family_identity::REFERENTS_FAMILY),
        )
    }
    pub fn migrations_family() -> sema_engine::TableDescriptor<Migration> {
        sema_engine::TableDescriptor::new(
            sema_engine::TableName::new("migrations"),
            sema_engine::FamilyName::new("MigrationsFamily"),
            sema_engine::SchemaHash::new(family_identity::MIGRATIONS_FAMILY),
        )
    }
    pub fn decode(
        identity: &sema_engine::FamilyIdentity,
        bytes: &[u8],
    ) -> Result<Self, RecordFamilyError> {
        match identity.family().as_str() {
            "RecordsFamily" => {
                let generated = sema_engine::SchemaHash::new(
                    family_identity::RECORDS_FAMILY,
                );
                if identity.schema_hash() != generated {
                    return Err(RecordFamilyError::SchemaHashMismatch {
                        family: sema_engine::FamilyName::new("RecordsFamily"),
                        stored: identity.schema_hash(),
                        generated,
                    });
                }
                let record = rkyv::from_bytes::<StoredRecord, rkyv::rancor::Error>(bytes)
                    .map_err(|_| RecordFamilyError::RecordDecode {
                        family: sema_engine::FamilyName::new("RecordsFamily"),
                    })?;
                Ok(Self::RecordsFamily(record))
            }
            "ReferentsFamily" => {
                let generated = sema_engine::SchemaHash::new(
                    family_identity::REFERENTS_FAMILY,
                );
                if identity.schema_hash() != generated {
                    return Err(RecordFamilyError::SchemaHashMismatch {
                        family: sema_engine::FamilyName::new("ReferentsFamily"),
                        stored: identity.schema_hash(),
                        generated,
                    });
                }
                let record = rkyv::from_bytes::<
                    StoredReferent,
                    rkyv::rancor::Error,
                >(bytes)
                    .map_err(|_| RecordFamilyError::RecordDecode {
                        family: sema_engine::FamilyName::new("ReferentsFamily"),
                    })?;
                Ok(Self::ReferentsFamily(record))
            }
            "MigrationsFamily" => {
                let generated = sema_engine::SchemaHash::new(
                    family_identity::MIGRATIONS_FAMILY,
                );
                if identity.schema_hash() != generated {
                    return Err(RecordFamilyError::SchemaHashMismatch {
                        family: sema_engine::FamilyName::new("MigrationsFamily"),
                        stored: identity.schema_hash(),
                        generated,
                    });
                }
                let record = rkyv::from_bytes::<Migration, rkyv::rancor::Error>(bytes)
                    .map_err(|_| RecordFamilyError::RecordDecode {
                        family: sema_engine::FamilyName::new("MigrationsFamily"),
                    })?;
                Ok(Self::MigrationsFamily(record))
            }
            _ => {
                Err(RecordFamilyError::UnknownFamily {
                    family: identity.family().clone(),
                })
            }
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum WriteInputRoute {
    Record,
    Remove,
    ChangeCertainty,
    BumpImportance,
    ChangeRecord,
    RegisterReferent,
}

#[rustfmt::skip]
impl WriteInput {
    pub fn route(&self) -> WriteInputRoute {
        match self {
            Self::Record(_) => WriteInputRoute::Record,
            Self::Remove(_) => WriteInputRoute::Remove,
            Self::ChangeCertainty(_) => WriteInputRoute::ChangeCertainty,
            Self::BumpImportance(_) => WriteInputRoute::BumpImportance,
            Self::ChangeRecord(_) => WriteInputRoute::ChangeRecord,
            Self::RegisterReferent(_) => WriteInputRoute::RegisterReferent,
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ReadInputRoute {
    Observe,
    PublicTextSearch,
    Lookup,
    Count,
}

#[rustfmt::skip]
impl ReadInput {
    pub fn route(&self) -> ReadInputRoute {
        match self {
            Self::Observe(_) => ReadInputRoute::Observe,
            Self::PublicTextSearch(_) => ReadInputRoute::PublicTextSearch,
            Self::Lookup(_) => ReadInputRoute::Lookup,
            Self::Count(_) => ReadInputRoute::Count,
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum WriteOutputRoute {
    Recorded,
    Removed,
    CertaintyChanged,
    ImportanceBumped,
    RecordChanged,
    ReferentRegistered,
    Missed,
}

#[rustfmt::skip]
impl WriteOutput {
    pub fn route(&self) -> WriteOutputRoute {
        match self {
            Self::Recorded(_) => WriteOutputRoute::Recorded,
            Self::Removed(_) => WriteOutputRoute::Removed,
            Self::CertaintyChanged(_) => WriteOutputRoute::CertaintyChanged,
            Self::ImportanceBumped(_) => WriteOutputRoute::ImportanceBumped,
            Self::RecordChanged(_) => WriteOutputRoute::RecordChanged,
            Self::ReferentRegistered(_) => WriteOutputRoute::ReferentRegistered,
            Self::Missed(_) => WriteOutputRoute::Missed,
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ReadOutputRoute {
    Observed,
    PublicTextSearchResults,
    Found,
    Counted,
    Missed,
}

#[rustfmt::skip]
impl ReadOutput {
    pub fn route(&self) -> ReadOutputRoute {
        match self {
            Self::Observed(_) => ReadOutputRoute::Observed,
            Self::PublicTextSearchResults(_) => ReadOutputRoute::PublicTextSearchResults,
            Self::Found(_) => ReadOutputRoute::Found,
            Self::Counted(_) => ReadOutputRoute::Counted,
            Self::Missed(_) => ReadOutputRoute::Missed,
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SemaObjectName {
    WriteInput(WriteInputRoute),
    ReadInput(ReadInputRoute),
    WriteOutput(WriteOutputRoute),
    ReadOutput(ReadOutputRoute),
    Started,
    Stopped,
    WriteApplied,
    ReadObserved,
}
#[rustfmt::skip]
impl SemaObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::WriteInput(route) => {
                match route {
                    WriteInputRoute::Record => "SemaWriteInputRecord",
                    WriteInputRoute::Remove => "SemaWriteInputRemove",
                    WriteInputRoute::ChangeCertainty => "SemaWriteInputChangeCertainty",
                    WriteInputRoute::BumpImportance => "SemaWriteInputBumpImportance",
                    WriteInputRoute::ChangeRecord => "SemaWriteInputChangeRecord",
                    WriteInputRoute::RegisterReferent => "SemaWriteInputRegisterReferent",
                }
            }
            Self::ReadInput(route) => {
                match route {
                    ReadInputRoute::Observe => "SemaReadInputObserve",
                    ReadInputRoute::PublicTextSearch => "SemaReadInputPublicTextSearch",
                    ReadInputRoute::Lookup => "SemaReadInputLookup",
                    ReadInputRoute::Count => "SemaReadInputCount",
                }
            }
            Self::WriteOutput(route) => {
                match route {
                    WriteOutputRoute::Recorded => "SemaWriteOutputRecorded",
                    WriteOutputRoute::Removed => "SemaWriteOutputRemoved",
                    WriteOutputRoute::CertaintyChanged => {
                        "SemaWriteOutputCertaintyChanged"
                    }
                    WriteOutputRoute::ImportanceBumped => {
                        "SemaWriteOutputImportanceBumped"
                    }
                    WriteOutputRoute::RecordChanged => "SemaWriteOutputRecordChanged",
                    WriteOutputRoute::ReferentRegistered => {
                        "SemaWriteOutputReferentRegistered"
                    }
                    WriteOutputRoute::Missed => "SemaWriteOutputMissed",
                }
            }
            Self::ReadOutput(route) => {
                match route {
                    ReadOutputRoute::Observed => "SemaReadOutputObserved",
                    ReadOutputRoute::PublicTextSearchResults => {
                        "SemaReadOutputPublicTextSearchResults"
                    }
                    ReadOutputRoute::Found => "SemaReadOutputFound",
                    ReadOutputRoute::Counted => "SemaReadOutputCounted",
                    ReadOutputRoute::Missed => "SemaReadOutputMissed",
                }
            }
            Self::Started => "SemaStarted",
            Self::Stopped => "SemaStopped",
            Self::WriteApplied => "SemaWriteApplied",
            Self::ReadObserved => "SemaReadObserved",
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ObjectName {
    Sema(SemaObjectName),
}
#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct TraceEvent(pub ObjectName);
#[rustfmt::skip]
impl ObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::Sema(object_name) => object_name.name(),
        }
    }
}
#[rustfmt::skip]
impl TraceEvent {
    pub fn new(object_name: ObjectName) -> Self {
        Self(object_name)
    }
    pub fn object_name(&self) -> ObjectName {
        self.0
    }
    pub fn name(&self) -> &'static str {
        self.0.name()
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct OriginRoute(Integer);
#[rustfmt::skip]
impl OriginRoute {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> Integer {
        self.0
    }
}

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Sema<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}
#[rustfmt::skip]
impl<Root> Sema<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }
    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }
    pub fn root(&self) -> &Root {
        &self.root
    }
    pub fn into_root(self) -> Root {
        self.root
    }
    pub fn map_root<NextRoot>(
        self,
        map: impl FnOnce(Root) -> NextRoot,
    ) -> Sema<NextRoot> {
        Sema::new(self.origin_route, map(self.root))
    }
}

#[rustfmt::skip]
#[allow(clippy::module_inception)]
pub mod sema {
    pub type WriteInput = super::WriteInput;
    pub type WriteOutput = super::WriteOutput;
    pub type ReadInput = super::ReadInput;
    pub type ReadOutput = super::ReadOutput;
    pub type Sema<Root> = super::Sema<Root>;
}

#[rustfmt::skip]
impl WriteInput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl WriteOutput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl ReadInput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl ReadOutput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl triad_runtime::SemaWriteInput for WriteInput {}

#[rustfmt::skip]
impl triad_runtime::SemaWriteOutput for WriteOutput {}

#[rustfmt::skip]
impl triad_runtime::SemaReadInput for ReadInput {}

#[rustfmt::skip]
impl triad_runtime::SemaReadOutput for ReadOutput {}

#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum EngineStartFailure {
    ResourceBusy(String),
    ConfigurationInvalid(String),
}
#[rustfmt::skip]
impl std::fmt::Display for EngineStartFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceBusy(message) => {
                write!(formatter, "engine resource busy: {message}")
            }
            Self::ConfigurationInvalid(message) => {
                write!(formatter, "engine configuration invalid: {message}")
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for EngineStartFailure {}
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum EngineStopFailure {
    ResourceLocked(String),
    ChildStillRunning(String),
}
#[rustfmt::skip]
impl std::fmt::Display for EngineStopFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceLocked(message) => {
                write!(formatter, "engine resource locked: {message}")
            }
            Self::ChildStillRunning(message) => {
                write!(formatter, "engine child still running: {message}")
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for EngineStopFailure {}

#[rustfmt::skip]
pub trait SemaEngine: Send {
    fn on_start(&mut self) -> Result<(), EngineStartFailure> {
        Ok(())
    }
    fn on_stop(&mut self) -> Result<(), EngineStopFailure> {
        Ok(())
    }
    fn trace_sema_activation(&self, _object_name: SemaObjectName) {}
    fn trace_sema_write_applied(&self) {
        self.trace_sema_activation(SemaObjectName::WriteApplied);
    }
    fn trace_sema_read_observed(&self) {
        self.trace_sema_activation(SemaObjectName::ReadObserved);
    }
    fn apply_inner(
        &mut self,
        input: sema::Sema<sema::WriteInput>,
    ) -> sema::Sema<sema::WriteOutput>;
    fn observe_inner(
        &self,
        input: sema::Sema<sema::ReadInput>,
    ) -> sema::Sema<sema::ReadOutput>;
    fn apply(
        &mut self,
        input: sema::Sema<sema::WriteInput>,
    ) -> sema::Sema<sema::WriteOutput> {
        let output = self.apply_inner(input);
        self.trace_sema_write_applied();
        output
    }
    fn observe(
        &self,
        input: sema::Sema<sema::ReadInput>,
    ) -> sema::Sema<sema::ReadOutput> {
        let output = self.observe_inner(input);
        self.trace_sema_read_observed();
        output
    }
}

#[rustfmt::skip]
pub trait UpgradeFrom<Previous>: Sized {
    type Error;
    fn upgrade_from(previous: Previous) -> Result<Self, Self::Error>;
}
#[rustfmt::skip]
pub trait AcceptPrevious<Previous>: UpgradeFrom<Previous> {
    fn accept_previous(previous: Previous) -> Result<Self, Self::Error> {
        Self::upgrade_from(previous)
    }
}
#[rustfmt::skip]
impl<Current, Previous> AcceptPrevious<Previous> for Current
where
    Current: UpgradeFrom<Previous>,
{}
