// @generated by schema-rust-next

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota_next::{NotaDecode, NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
pub type SourcePath = String;

#[rustfmt::skip]
pub type LocalPath = String;

#[rustfmt::skip]
pub type PublicPath = String;

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Import {
    pub source_path: SourcePath,
    pub local_path: LocalPath,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Export {
    pub local_path: LocalPath,
    pub public_path: PublicPath,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SignalReuse {
    pub import: Import,
    pub export: Export,
}

#[rustfmt::skip]
pub type State = Statement;

#[rustfmt::skip]
pub type Record = Entry;

#[rustfmt::skip]
pub type Observe = Query;

#[rustfmt::skip]
pub type PublicRecords = RecordSelection;

#[rustfmt::skip]
pub type PrivateRecords = RecordSelection;

#[rustfmt::skip]
pub type Lookup = RecordIdentifier;

#[rustfmt::skip]
pub type Count = Query;

#[rustfmt::skip]
pub type Remove = RecordIdentifier;

#[rustfmt::skip]
pub type ChangeCertainty = CertaintyChange;

#[rustfmt::skip]
pub type ChangeRecord = RecordChange;

#[rustfmt::skip]
pub type LookupStash = StashHandle;

#[rustfmt::skip]
pub type CollectRemovalCandidates = RemovalCandidateCollection;

#[rustfmt::skip]
pub type Tap = ObserverFilter;

#[rustfmt::skip]
pub type Untap = SubscriptionToken;

#[rustfmt::skip]
pub type SubscribeIntent = Query;

#[rustfmt::skip]
pub type RecordAccepted = SemaReceipt;

#[rustfmt::skip]
pub type RecordsObserved = ObservedRecords;

#[rustfmt::skip]
pub type RecordsStashed = StashedObservation;

#[rustfmt::skip]
pub type RecordFound = FoundRecord;

#[rustfmt::skip]
pub type RecordsCounted = CountedRecords;

#[rustfmt::skip]
pub type RecordRemoved = RemoveReceipt;

#[rustfmt::skip]
pub type CertaintyChanged = CertaintyChangeReceipt;

#[rustfmt::skip]
pub type RecordChanged = RecordChangeReceipt;

#[rustfmt::skip]
pub type RemovalCandidatesCollected = RemovalCandidatesCollection;

#[rustfmt::skip]
pub type ObservationTapped = ObserverSubscription;

#[rustfmt::skip]
pub type ObservationUntapped = ObserverRetraction;

#[rustfmt::skip]
pub type SubscriptionStarted = IntentSubscription;

#[rustfmt::skip]
pub type Error = ErrorReport;

#[rustfmt::skip]
pub type Rejected = SignalRejection;

#[rustfmt::skip]
pub type Topic = String;

#[rustfmt::skip]
pub type Topics = Vec<Topic>;

#[rustfmt::skip]
pub type Description = String;

#[rustfmt::skip]
pub type StatementText = String;

#[rustfmt::skip]
pub type ErrorMessage = String;

#[rustfmt::skip]
pub type RecordIdentifier = String;

#[rustfmt::skip]
pub type CommitSequence = Integer;

#[rustfmt::skip]
pub type StateDigest = Integer;

#[rustfmt::skip]
pub type RecordCount = Integer;

#[rustfmt::skip]
pub type StashHandle = Integer;

#[rustfmt::skip]
pub type SubscriptionToken = Integer;

#[rustfmt::skip]
pub type MailIdentifier = Integer;

#[rustfmt::skip]
pub type ShortHeader = Integer;

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DatabaseMarker {
    pub commit_sequence: CommitSequence,
    pub state_digest: StateDigest,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SemaReceipt {
    pub record_identifier: RecordIdentifier,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RemoveReceipt {
    pub record_identifier: RecordIdentifier,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ObservedRecords {
    pub record_set: RecordSet,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct FoundRecord {
    pub record_identifier: RecordIdentifier,
    pub entry: Entry,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CountedRecords {
    pub record_count: RecordCount,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ErrorReport {
    pub error_message: ErrorMessage,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SignalRejection {
    pub validation_error: ValidationError,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StashedObservation {
    pub stash_handle: StashHandle,
    pub record_count: RecordCount,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct IntentSubscription {
    pub subscription_token: SubscriptionToken,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct IntentRecorded {
    pub entry: Entry,
    pub sema_receipt: SemaReceipt,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum IntentEvent {
    IntentRecorded(IntentRecorded),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ValidationError {
    EmptyTopic,
    EmptyDescription,
    EmptyQueryTopic,
    StashHandleNotFound,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SentMail {
    pub mail_identifier: MailIdentifier,
    pub origin_route: OriginRoute,
    pub short_header: ShortHeader,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ProcessedMail {
    pub mail_identifier: MailIdentifier,
    pub origin_route: OriginRoute,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum MailLedgerEvent {
    Sent(Sent),
    Processed(Processed),
}

#[rustfmt::skip]
pub type Sent = SentMail;

#[rustfmt::skip]
pub type Processed = ProcessedMail;

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum TopicMatch {
    Any,
    Partial(Partial),
    Full(Full),
}

#[rustfmt::skip]
pub type Partial = Topics;

#[rustfmt::skip]
pub type Full = Topics;

#[rustfmt::skip]
pub type Privacy = Magnitude;

#[rustfmt::skip]
pub type Certainty = Magnitude;

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum PrivacySelection {
    Any,
    Exact(Exact),
    AtMost(AtMost),
    AtLeast(AtLeast),
}

#[rustfmt::skip]
pub type Exact = Privacy;

#[rustfmt::skip]
pub type AtMost = Privacy;

#[rustfmt::skip]
pub type AtLeast = Privacy;

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RemovalCandidateCollection(pub RecordQuery);

#[rustfmt::skip]
pub type RecordQuery = Query;

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ArchivedRecord {
    pub record_identifier: RecordIdentifier,
    pub entry: Entry,
}

#[rustfmt::skip]
pub type ArchivedRecords = Vec<ArchivedRecord>;

#[rustfmt::skip]
pub type RemovedIdentifier = RecordIdentifier;

#[rustfmt::skip]
pub type RemovedIdentifiers = Vec<RemovedIdentifier>;

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum RemovalCandidateSkipReason {
    ArchiveFailed,
    RecordChanged,
    RecordAlreadyRemoved,
    NoLongerCandidate,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SkippedRemovalCandidate {
    pub record_identifier: RecordIdentifier,
    pub removal_candidate_skip_reason: RemovalCandidateSkipReason,
}

#[rustfmt::skip]
pub type SkippedRemovalCandidates = Vec<SkippedRemovalCandidate>;

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RemovalCandidatesCollection {
    pub archived_records: ArchivedRecords,
    pub removed_identifiers: RemovedIdentifiers,
    pub skipped_removal_candidates: SkippedRemovalCandidates,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ObserverFilter {
    All,
    OperationsOnly,
    EffectsOnly,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ObserverSubscription {
    pub subscription_token: SubscriptionToken,
    pub observer_filter: ObserverFilter,
    pub observed_operations: ObservedOperations,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ObserverRetraction {
    pub subscription_token: SubscriptionToken,
    pub observed_operations: ObservedOperations,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OperationKind {
    State,
    Record,
    Observe,
    PublicRecords,
    PrivateRecords,
    Lookup,
    Count,
    Remove,
    ChangeCertainty,
    ChangeRecord,
    LookupStash,
    CollectRemovalCandidates,
    Tap,
    Untap,
    SubscribeIntent,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ObservedOperation(pub OperationKind);

#[rustfmt::skip]
pub type ObservedOperations = Vec<ObservedOperation>;

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Entry {
    pub topics: Topics,
    pub kind: Kind,
    pub description: Description,
    pub magnitude: Magnitude,
    pub privacy: Privacy,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Statement(pub StatementText);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CertaintyChange {
    pub record_identifier: RecordIdentifier,
    pub certainty: Certainty,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CertaintyChangeReceipt {
    pub record_identifier: RecordIdentifier,
    pub certainty: Certainty,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RecordChange {
    pub record_identifier: RecordIdentifier,
    pub entry: Entry,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RecordChangeReceipt {
    pub record_identifier: RecordIdentifier,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RecordSelection {
    pub topic_match: TopicMatch,
    pub kind: Option<Kind>,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Query {
    pub topic_match: TopicMatch,
    pub kind: Option<Kind>,
    pub privacy_selection: PrivacySelection,
}

#[rustfmt::skip]
pub type Records = Vec<Entry>;

#[rustfmt::skip]
pub type RecordSet = Vec<Entry>;

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum Kind {
    Decision,
    Principle,
    Correction,
    Clarification,
    Constraint,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum Magnitude {
    Zero,
    Minimum,
    VeryLow,
    Low,
    Medium,
    High,
    VeryHigh,
    Maximum,
}

#[rustfmt::skip]
pub type ConfigurationPath = String;

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Configuration {
    pub socket_path: ConfigurationPath,
    pub meta_socket_path: Option<ConfigurationPath>,
    pub database_path: ConfigurationPath,
    pub trace_socket_path: Option<ConfigurationPath>,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    State(State),
    Record(Record),
    Observe(Observe),
    PublicRecords(PublicRecords),
    PrivateRecords(PrivateRecords),
    Lookup(Lookup),
    Count(Count),
    Remove(Remove),
    ChangeCertainty(ChangeCertainty),
    ChangeRecord(ChangeRecord),
    LookupStash(LookupStash),
    CollectRemovalCandidates(CollectRemovalCandidates),
    Tap(Tap),
    Untap(Untap),
    SubscribeIntent(SubscribeIntent),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    RecordAccepted(RecordAccepted),
    RecordsObserved(RecordsObserved),
    RecordsStashed(RecordsStashed),
    RecordFound(RecordFound),
    RecordsCounted(RecordsCounted),
    RecordRemoved(RecordRemoved),
    CertaintyChanged(CertaintyChanged),
    RecordChanged(RecordChanged),
    RemovalCandidatesCollected(RemovalCandidatesCollected),
    ObservationTapped(ObservationTapped),
    ObservationUntapped(ObservationUntapped),
    SubscriptionStarted(SubscriptionStarted),
    Event(IntentEvent),
    Error(Error),
    Rejected(Rejected),
}

#[rustfmt::skip]
impl RemovalCandidateCollection {
    pub fn new(payload: RecordQuery) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RecordQuery {
        &self.0
    }
    pub fn into_payload(self) -> RecordQuery {
        self.0
    }
}
#[rustfmt::skip]
impl From<RecordQuery> for RemovalCandidateCollection {
    fn from(payload: RecordQuery) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ObservedOperation {
    pub fn new(payload: OperationKind) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &OperationKind {
        &self.0
    }
    pub fn into_payload(self) -> OperationKind {
        self.0
    }
}
#[rustfmt::skip]
impl From<OperationKind> for ObservedOperation {
    fn from(payload: OperationKind) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Statement {
    pub fn new(payload: StatementText) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &StatementText {
        &self.0
    }
    pub fn into_payload(self) -> StatementText {
        self.0
    }
}
#[rustfmt::skip]
impl From<StatementText> for Statement {
    fn from(payload: StatementText) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl IntentEvent {
    pub fn intent_recorded(payload: IntentRecorded) -> Self {
        Self::IntentRecorded(payload)
    }
}

#[rustfmt::skip]
impl MailLedgerEvent {
    pub fn sent(payload: Sent) -> Self {
        Self::Sent(payload)
    }
    pub fn processed(payload: Processed) -> Self {
        Self::Processed(payload)
    }
}

#[rustfmt::skip]
impl TopicMatch {
    pub fn partial(payload: Partial) -> Self {
        Self::Partial(payload)
    }
    pub fn full(payload: Full) -> Self {
        Self::Full(payload)
    }
}

#[rustfmt::skip]
impl PrivacySelection {
    pub fn exact(payload: Exact) -> Self {
        Self::Exact(payload)
    }
    pub fn at_most(payload: AtMost) -> Self {
        Self::AtMost(payload)
    }
    pub fn at_least(payload: AtLeast) -> Self {
        Self::AtLeast(payload)
    }
}

#[rustfmt::skip]
impl Input {
    pub fn state(payload: State) -> Self {
        Self::State(payload)
    }
    pub fn record(payload: Record) -> Self {
        Self::Record(payload)
    }
    pub fn observe(payload: Observe) -> Self {
        Self::Observe(payload)
    }
    pub fn public_records(payload: PublicRecords) -> Self {
        Self::PublicRecords(payload)
    }
    pub fn private_records(payload: PrivateRecords) -> Self {
        Self::PrivateRecords(payload)
    }
    pub fn lookup(payload: Lookup) -> Self {
        Self::Lookup(payload)
    }
    pub fn count(payload: Count) -> Self {
        Self::Count(payload)
    }
    pub fn remove(payload: Remove) -> Self {
        Self::Remove(payload)
    }
    pub fn change_certainty(payload: ChangeCertainty) -> Self {
        Self::ChangeCertainty(payload)
    }
    pub fn change_record(payload: ChangeRecord) -> Self {
        Self::ChangeRecord(payload)
    }
    pub fn lookup_stash(payload: LookupStash) -> Self {
        Self::LookupStash(payload)
    }
    pub fn collect_removal_candidates(payload: CollectRemovalCandidates) -> Self {
        Self::CollectRemovalCandidates(payload)
    }
    pub fn tap(payload: Tap) -> Self {
        Self::Tap(payload)
    }
    pub fn untap(payload: Untap) -> Self {
        Self::Untap(payload)
    }
    pub fn subscribe_intent(payload: SubscribeIntent) -> Self {
        Self::SubscribeIntent(payload)
    }
}

#[rustfmt::skip]
impl Output {
    pub fn record_accepted(payload: RecordAccepted) -> Self {
        Self::RecordAccepted(payload)
    }
    pub fn records_observed(payload: RecordsObserved) -> Self {
        Self::RecordsObserved(payload)
    }
    pub fn records_stashed(payload: RecordsStashed) -> Self {
        Self::RecordsStashed(payload)
    }
    pub fn record_found(payload: RecordFound) -> Self {
        Self::RecordFound(payload)
    }
    pub fn records_counted(payload: RecordsCounted) -> Self {
        Self::RecordsCounted(payload)
    }
    pub fn record_removed(payload: RecordRemoved) -> Self {
        Self::RecordRemoved(payload)
    }
    pub fn certainty_changed(payload: CertaintyChanged) -> Self {
        Self::CertaintyChanged(payload)
    }
    pub fn record_changed(payload: RecordChanged) -> Self {
        Self::RecordChanged(payload)
    }
    pub fn removal_candidates_collected(payload: RemovalCandidatesCollected) -> Self {
        Self::RemovalCandidatesCollected(payload)
    }
    pub fn observation_tapped(payload: ObservationTapped) -> Self {
        Self::ObservationTapped(payload)
    }
    pub fn observation_untapped(payload: ObservationUntapped) -> Self {
        Self::ObservationUntapped(payload)
    }
    pub fn subscription_started(payload: SubscriptionStarted) -> Self {
        Self::SubscriptionStarted(payload)
    }
    pub fn event(payload: IntentEvent) -> Self {
        Self::Event(payload)
    }
    pub fn error(payload: Error) -> Self {
        Self::Error(payload)
    }
    pub fn rejected(payload: Rejected) -> Self {
        Self::Rejected(payload)
    }
}

#[rustfmt::skip]
impl From<IntentRecorded> for IntentEvent {
    fn from(payload: IntentRecorded) -> Self {
        Self::IntentRecorded(payload)
    }
}

#[rustfmt::skip]
impl From<IntentEvent> for Output {
    fn from(payload: IntentEvent) -> Self {
        Self::Event(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Import {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Export {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl SignalReuse {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl DatabaseMarker {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl SemaReceipt {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl RemoveReceipt {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ObservedRecords {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl FoundRecord {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl CountedRecords {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ErrorReport {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl SignalRejection {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl StashedObservation {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl IntentSubscription {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl IntentRecorded {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl IntentEvent {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ValidationError {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(self) -> String {
        <Self as NotaEncode>::to_nota(&self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl SentMail {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ProcessedMail {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl MailLedgerEvent {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl TopicMatch {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl PrivacySelection {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl RemovalCandidateCollection {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ArchivedRecord {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl RemovalCandidateSkipReason {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(self) -> String {
        <Self as NotaEncode>::to_nota(&self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl SkippedRemovalCandidate {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl RemovalCandidatesCollection {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ObserverFilter {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(self) -> String {
        <Self as NotaEncode>::to_nota(&self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ObserverSubscription {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ObserverRetraction {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl OperationKind {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(self) -> String {
        <Self as NotaEncode>::to_nota(&self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ObservedOperation {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Entry {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Statement {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl CertaintyChange {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl CertaintyChangeReceipt {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl RecordChange {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl RecordChangeReceipt {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl RecordSelection {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Query {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Kind {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(self) -> String {
        <Self as NotaEncode>::to_nota(&self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Magnitude {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(self) -> String {
        <Self as NotaEncode>::to_nota(&self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Configuration {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Input {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Output {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
pub mod short_header {
    pub const INPUT_STATE: u64 = 0x0000000000000000;
    pub const INPUT_RECORD: u64 = 0x0001000000000000;
    pub const INPUT_OBSERVE: u64 = 0x0002000000000000;
    pub const INPUT_PUBLIC_RECORDS: u64 = 0x0003000000000000;
    pub const INPUT_PRIVATE_RECORDS: u64 = 0x0004000000000000;
    pub const INPUT_LOOKUP: u64 = 0x0005000000000000;
    pub const INPUT_COUNT: u64 = 0x0006000000000000;
    pub const INPUT_REMOVE: u64 = 0x0007000000000000;
    pub const INPUT_CHANGE_CERTAINTY: u64 = 0x0008000000000000;
    pub const INPUT_CHANGE_RECORD: u64 = 0x0009000000000000;
    pub const INPUT_LOOKUP_STASH: u64 = 0x000A000000000000;
    pub const INPUT_COLLECT_REMOVAL_CANDIDATES: u64 = 0x000B000000000000;
    pub const INPUT_TAP: u64 = 0x000C000000000000;
    pub const INPUT_UNTAP: u64 = 0x000D000000000000;
    pub const INPUT_SUBSCRIBE_INTENT: u64 = 0x000E000000000000;
    pub const OUTPUT_RECORD_ACCEPTED: u64 = 0x0100000000000000;
    pub const OUTPUT_RECORDS_OBSERVED: u64 = 0x0101000000000000;
    pub const OUTPUT_RECORDS_STASHED: u64 = 0x0102000000000000;
    pub const OUTPUT_RECORD_FOUND: u64 = 0x0103000000000000;
    pub const OUTPUT_RECORDS_COUNTED: u64 = 0x0104000000000000;
    pub const OUTPUT_RECORD_REMOVED: u64 = 0x0105000000000000;
    pub const OUTPUT_CERTAINTY_CHANGED: u64 = 0x0106000000000000;
    pub const OUTPUT_RECORD_CHANGED: u64 = 0x0107000000000000;
    pub const OUTPUT_REMOVAL_CANDIDATES_COLLECTED: u64 = 0x0108000000000000;
    pub const OUTPUT_OBSERVATION_TAPPED: u64 = 0x0109000000000000;
    pub const OUTPUT_OBSERVATION_UNTAPPED: u64 = 0x010A000000000000;
    pub const OUTPUT_SUBSCRIPTION_STARTED: u64 = 0x010B000000000000;
    pub const OUTPUT_EVENT: u64 = 0x010C000000000000;
    pub const OUTPUT_ERROR: u64 = 0x010D000000000000;
    pub const OUTPUT_REJECTED: u64 = 0x010E000000000000;
}

#[rustfmt::skip]
const SIGNAL_SHORT_HEADER_BYTE_COUNT: usize = 8;
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    UnknownHeader { root_enum: &'static str, header: u64 },
    HeaderMismatch { expected: u64, found: u64 },
}
#[rustfmt::skip]
impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => {
                write!(formatter, "signal frame too short: {found} bytes")
            }
            Self::UnknownHeader { root_enum, header } => {
                write!(formatter, "unknown {root_enum} short header 0x{header:016X}")
            }
            Self::HeaderMismatch { expected, found } => {
                write!(
                    formatter,
                    "decoded payload header mismatch: expected 0x{expected:016X}, found 0x{found:016X}"
                )
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for SignalFrameError {}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum InputRoute {
    State,
    Record,
    Observe,
    PublicRecords,
    PrivateRecords,
    Lookup,
    Count,
    Remove,
    ChangeCertainty,
    ChangeRecord,
    LookupStash,
    CollectRemovalCandidates,
    Tap,
    Untap,
    SubscribeIntent,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OutputRoute {
    RecordAccepted,
    RecordsObserved,
    RecordsStashed,
    RecordFound,
    RecordsCounted,
    RecordRemoved,
    CertaintyChanged,
    RecordChanged,
    RemovalCandidatesCollected,
    ObservationTapped,
    ObservationUntapped,
    SubscriptionStarted,
    Event,
    Error,
    Rejected,
}

#[rustfmt::skip]
impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::State(_) => InputRoute::State,
            Self::Record(_) => InputRoute::Record,
            Self::Observe(_) => InputRoute::Observe,
            Self::PublicRecords(_) => InputRoute::PublicRecords,
            Self::PrivateRecords(_) => InputRoute::PrivateRecords,
            Self::Lookup(_) => InputRoute::Lookup,
            Self::Count(_) => InputRoute::Count,
            Self::Remove(_) => InputRoute::Remove,
            Self::ChangeCertainty(_) => InputRoute::ChangeCertainty,
            Self::ChangeRecord(_) => InputRoute::ChangeRecord,
            Self::LookupStash(_) => InputRoute::LookupStash,
            Self::CollectRemovalCandidates(_) => InputRoute::CollectRemovalCandidates,
            Self::Tap(_) => InputRoute::Tap,
            Self::Untap(_) => InputRoute::Untap,
            Self::SubscribeIntent(_) => InputRoute::SubscribeIntent,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::State(_) => short_header::INPUT_STATE,
            Self::Record(_) => short_header::INPUT_RECORD,
            Self::Observe(_) => short_header::INPUT_OBSERVE,
            Self::PublicRecords(_) => short_header::INPUT_PUBLIC_RECORDS,
            Self::PrivateRecords(_) => short_header::INPUT_PRIVATE_RECORDS,
            Self::Lookup(_) => short_header::INPUT_LOOKUP,
            Self::Count(_) => short_header::INPUT_COUNT,
            Self::Remove(_) => short_header::INPUT_REMOVE,
            Self::ChangeCertainty(_) => short_header::INPUT_CHANGE_CERTAINTY,
            Self::ChangeRecord(_) => short_header::INPUT_CHANGE_RECORD,
            Self::LookupStash(_) => short_header::INPUT_LOOKUP_STASH,
            Self::CollectRemovalCandidates(_) => {
                short_header::INPUT_COLLECT_REMOVAL_CANDIDATES
            }
            Self::Tap(_) => short_header::INPUT_TAP,
            Self::Untap(_) => short_header::INPUT_UNTAP,
            Self::SubscribeIntent(_) => short_header::INPUT_SUBSCRIBE_INTENT,
        }
    }
    pub fn route_from_short_header(header: u64) -> Result<InputRoute, SignalFrameError> {
        match header {
            short_header::INPUT_STATE => Ok(InputRoute::State),
            short_header::INPUT_RECORD => Ok(InputRoute::Record),
            short_header::INPUT_OBSERVE => Ok(InputRoute::Observe),
            short_header::INPUT_PUBLIC_RECORDS => Ok(InputRoute::PublicRecords),
            short_header::INPUT_PRIVATE_RECORDS => Ok(InputRoute::PrivateRecords),
            short_header::INPUT_LOOKUP => Ok(InputRoute::Lookup),
            short_header::INPUT_COUNT => Ok(InputRoute::Count),
            short_header::INPUT_REMOVE => Ok(InputRoute::Remove),
            short_header::INPUT_CHANGE_CERTAINTY => Ok(InputRoute::ChangeCertainty),
            short_header::INPUT_CHANGE_RECORD => Ok(InputRoute::ChangeRecord),
            short_header::INPUT_LOOKUP_STASH => Ok(InputRoute::LookupStash),
            short_header::INPUT_COLLECT_REMOVAL_CANDIDATES => {
                Ok(InputRoute::CollectRemovalCandidates)
            }
            short_header::INPUT_TAP => Ok(InputRoute::Tap),
            short_header::INPUT_UNTAP => Ok(InputRoute::Untap),
            short_header::INPUT_SUBSCRIBE_INTENT => Ok(InputRoute::SubscribeIntent),
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Input",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(InputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::RecordAccepted(_) => OutputRoute::RecordAccepted,
            Self::RecordsObserved(_) => OutputRoute::RecordsObserved,
            Self::RecordsStashed(_) => OutputRoute::RecordsStashed,
            Self::RecordFound(_) => OutputRoute::RecordFound,
            Self::RecordsCounted(_) => OutputRoute::RecordsCounted,
            Self::RecordRemoved(_) => OutputRoute::RecordRemoved,
            Self::CertaintyChanged(_) => OutputRoute::CertaintyChanged,
            Self::RecordChanged(_) => OutputRoute::RecordChanged,
            Self::RemovalCandidatesCollected(_) => {
                OutputRoute::RemovalCandidatesCollected
            }
            Self::ObservationTapped(_) => OutputRoute::ObservationTapped,
            Self::ObservationUntapped(_) => OutputRoute::ObservationUntapped,
            Self::SubscriptionStarted(_) => OutputRoute::SubscriptionStarted,
            Self::Event(_) => OutputRoute::Event,
            Self::Error(_) => OutputRoute::Error,
            Self::Rejected(_) => OutputRoute::Rejected,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::RecordAccepted(_) => short_header::OUTPUT_RECORD_ACCEPTED,
            Self::RecordsObserved(_) => short_header::OUTPUT_RECORDS_OBSERVED,
            Self::RecordsStashed(_) => short_header::OUTPUT_RECORDS_STASHED,
            Self::RecordFound(_) => short_header::OUTPUT_RECORD_FOUND,
            Self::RecordsCounted(_) => short_header::OUTPUT_RECORDS_COUNTED,
            Self::RecordRemoved(_) => short_header::OUTPUT_RECORD_REMOVED,
            Self::CertaintyChanged(_) => short_header::OUTPUT_CERTAINTY_CHANGED,
            Self::RecordChanged(_) => short_header::OUTPUT_RECORD_CHANGED,
            Self::RemovalCandidatesCollected(_) => {
                short_header::OUTPUT_REMOVAL_CANDIDATES_COLLECTED
            }
            Self::ObservationTapped(_) => short_header::OUTPUT_OBSERVATION_TAPPED,
            Self::ObservationUntapped(_) => short_header::OUTPUT_OBSERVATION_UNTAPPED,
            Self::SubscriptionStarted(_) => short_header::OUTPUT_SUBSCRIPTION_STARTED,
            Self::Event(_) => short_header::OUTPUT_EVENT,
            Self::Error(_) => short_header::OUTPUT_ERROR,
            Self::Rejected(_) => short_header::OUTPUT_REJECTED,
        }
    }
    pub fn route_from_short_header(
        header: u64,
    ) -> Result<OutputRoute, SignalFrameError> {
        match header {
            short_header::OUTPUT_RECORD_ACCEPTED => Ok(OutputRoute::RecordAccepted),
            short_header::OUTPUT_RECORDS_OBSERVED => Ok(OutputRoute::RecordsObserved),
            short_header::OUTPUT_RECORDS_STASHED => Ok(OutputRoute::RecordsStashed),
            short_header::OUTPUT_RECORD_FOUND => Ok(OutputRoute::RecordFound),
            short_header::OUTPUT_RECORDS_COUNTED => Ok(OutputRoute::RecordsCounted),
            short_header::OUTPUT_RECORD_REMOVED => Ok(OutputRoute::RecordRemoved),
            short_header::OUTPUT_CERTAINTY_CHANGED => Ok(OutputRoute::CertaintyChanged),
            short_header::OUTPUT_RECORD_CHANGED => Ok(OutputRoute::RecordChanged),
            short_header::OUTPUT_REMOVAL_CANDIDATES_COLLECTED => {
                Ok(OutputRoute::RemovalCandidatesCollected)
            }
            short_header::OUTPUT_OBSERVATION_TAPPED => Ok(OutputRoute::ObservationTapped),
            short_header::OUTPUT_OBSERVATION_UNTAPPED => {
                Ok(OutputRoute::ObservationUntapped)
            }
            short_header::OUTPUT_SUBSCRIPTION_STARTED => {
                Ok(OutputRoute::SubscriptionStarted)
            }
            short_header::OUTPUT_EVENT => Ok(OutputRoute::Event),
            short_header::OUTPUT_ERROR => Ok(OutputRoute::Error),
            short_header::OUTPUT_REJECTED => Ok(OutputRoute::Rejected),
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Output",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(OutputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl signal_frame::RequestPayload for Input {}
#[rustfmt::skip]
impl signal_frame::SignalOperationHeads for Input {
    const HEADS: &'static [&'static str] = &[
        "State",
        "Record",
        "Observe",
        "PublicRecords",
        "PrivateRecords",
        "Lookup",
        "Count",
        "Remove",
        "ChangeCertainty",
        "ChangeRecord",
        "LookupStash",
        "CollectRemovalCandidates",
        "Tap",
        "Untap",
        "SubscribeIntent",
    ];
}
#[rustfmt::skip]
impl signal_frame::LogVariant for Input {
    fn log_variant(&self) -> u64 {
        self.short_header()
    }
}
#[rustfmt::skip]
pub type Frame = signal_frame::StreamingFrame<Input, Output, IntentEvent>;
#[rustfmt::skip]
pub type FrameBody = signal_frame::StreamingFrameBody<Input, Output, IntentEvent>;
#[rustfmt::skip]
pub type Request = signal_frame::Request<Input>;
#[rustfmt::skip]
pub type ReplyEnvelope = signal_frame::Reply<Output>;
#[rustfmt::skip]
pub type RequestBuilder = signal_frame::RequestBuilder<Input>;
#[rustfmt::skip]
impl Input {
    pub fn into_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let request = signal_frame::Request::from_payload(self);
        Frame::with_short_header(
            short_header,
            FrameBody::Request {
                exchange,
                request,
            },
        )
    }
}
#[rustfmt::skip]
impl Output {
    pub fn into_reply_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let reply = signal_frame::Reply::committed(
            signal_frame::NonEmpty::single(signal_frame::SubReply::Ok(self)),
        );
        Frame::with_short_header(
            short_header,
            FrameBody::Reply {
                exchange,
                reply,
            },
        )
    }
}

#[rustfmt::skip]
impl IntentEvent {
    pub fn into_subscription_frame(
        self,
        event_identifier: signal_frame::StreamEventIdentifier,
        token: signal_frame::SubscriptionTokenInner,
    ) -> Frame {
        Frame::with_short_header(
            signal_frame::ShortHeader::new(short_header::OUTPUT_EVENT),
            FrameBody::SubscriptionEvent {
                event_identifier,
                token,
                event: self,
            },
        )
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SignalObjectName {
    Input(InputRoute),
    Output(OutputRoute),
    Started,
    Stopped,
    Admitted,
    Rejected,
    Triaged,
    Replied,
}
#[rustfmt::skip]
impl SignalObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::Input(route) => {
                match route {
                    InputRoute::State => "SignalInputState",
                    InputRoute::Record => "SignalInputRecord",
                    InputRoute::Observe => "SignalInputObserve",
                    InputRoute::PublicRecords => "SignalInputPublicRecords",
                    InputRoute::PrivateRecords => "SignalInputPrivateRecords",
                    InputRoute::Lookup => "SignalInputLookup",
                    InputRoute::Count => "SignalInputCount",
                    InputRoute::Remove => "SignalInputRemove",
                    InputRoute::ChangeCertainty => "SignalInputChangeCertainty",
                    InputRoute::ChangeRecord => "SignalInputChangeRecord",
                    InputRoute::LookupStash => "SignalInputLookupStash",
                    InputRoute::CollectRemovalCandidates => {
                        "SignalInputCollectRemovalCandidates"
                    }
                    InputRoute::Tap => "SignalInputTap",
                    InputRoute::Untap => "SignalInputUntap",
                    InputRoute::SubscribeIntent => "SignalInputSubscribeIntent",
                }
            }
            Self::Output(route) => {
                match route {
                    OutputRoute::RecordAccepted => "SignalOutputRecordAccepted",
                    OutputRoute::RecordsObserved => "SignalOutputRecordsObserved",
                    OutputRoute::RecordsStashed => "SignalOutputRecordsStashed",
                    OutputRoute::RecordFound => "SignalOutputRecordFound",
                    OutputRoute::RecordsCounted => "SignalOutputRecordsCounted",
                    OutputRoute::RecordRemoved => "SignalOutputRecordRemoved",
                    OutputRoute::CertaintyChanged => "SignalOutputCertaintyChanged",
                    OutputRoute::RecordChanged => "SignalOutputRecordChanged",
                    OutputRoute::RemovalCandidatesCollected => {
                        "SignalOutputRemovalCandidatesCollected"
                    }
                    OutputRoute::ObservationTapped => "SignalOutputObservationTapped",
                    OutputRoute::ObservationUntapped => "SignalOutputObservationUntapped",
                    OutputRoute::SubscriptionStarted => "SignalOutputSubscriptionStarted",
                    OutputRoute::Event => "SignalOutputEvent",
                    OutputRoute::Error => "SignalOutputError",
                    OutputRoute::Rejected => "SignalOutputRejected",
                }
            }
            Self::Started => "SignalStarted",
            Self::Stopped => "SignalStopped",
            Self::Admitted => "SignalAdmitted",
            Self::Rejected => "SignalRejected",
            Self::Triaged => "SignalTriaged",
            Self::Replied => "SignalReplied",
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ObjectName {
    Signal(SignalObjectName),
}
#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct TraceEvent(pub ObjectName);
#[rustfmt::skip]
impl ObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::Signal(object_name) => object_name.name(),
        }
    }
}
#[rustfmt::skip]
impl TraceEvent {
    pub fn new(object_name: ObjectName) -> Self {
        Self(object_name)
    }
    pub fn object_name(&self) -> ObjectName {
        self.0
    }
    pub fn name(&self) -> &'static str {
        self.0.name()
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct MessageIdentifier(pub Integer);
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl MessageIdentifier {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(self) -> String {
        <Self as NotaEncode>::to_nota(&self)
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct OriginRoute(pub Integer);
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl OriginRoute {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(self) -> String {
        <Self as NotaEncode>::to_nota(&self)
    }
}

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Signal<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}
#[rustfmt::skip]
impl<Root> Signal<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }
    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }
    pub fn root(&self) -> &Root {
        &self.root
    }
    pub fn into_root(self) -> Root {
        self.root
    }
    pub fn map_root<NextRoot>(
        self,
        map: impl FnOnce(Root) -> NextRoot,
    ) -> Signal<NextRoot> {
        Signal::new(self.origin_route, map(self.root))
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum MessageRoot {
    Input,
    Output,
}

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MessageSent {
    pub identifier: MessageIdentifier,
    pub origin_route: OriginRoute,
    pub root: MessageRoot,
    pub short_header: Integer,
}
#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MessageProcessed<Reply> {
    pub identifier: MessageIdentifier,
    pub origin_route: OriginRoute,
    pub reply: Reply,
}
#[rustfmt::skip]
pub trait MessageSentHook {
    type Error;
    fn message_sent(&mut self, event: MessageSent) -> Result<(), Self::Error>;
}
#[rustfmt::skip]
pub trait MessageProcessedHook<Reply> {
    type Error;
    fn message_processed(
        &mut self,
        event: MessageProcessed<Reply>,
    ) -> Result<(), Self::Error>;
}
#[rustfmt::skip]
impl MessageSent {
    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }
    pub fn push_to<Hook>(&self, hook: &mut Hook) -> Result<(), Hook::Error>
    where
        Hook: MessageSentHook,
    {
        hook.message_sent(self.clone())
    }
}
#[rustfmt::skip]
impl<Reply> MessageProcessed<Reply> {
    pub fn new(
        identifier: MessageIdentifier,
        origin_route: OriginRoute,
        reply: Reply,
    ) -> Self {
        Self {
            identifier,
            origin_route,
            reply,
        }
    }
    pub fn identifier(&self) -> MessageIdentifier {
        self.identifier
    }
    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }
    pub fn into_reply(self) -> Reply {
        self.reply
    }
    pub fn push_to<Hook>(&self, hook: &mut Hook) -> Result<(), Hook::Error>
    where
        Hook: MessageProcessedHook<Reply>,
        Reply: Clone,
    {
        hook.message_processed(self.clone())
    }
}
#[rustfmt::skip]
impl Input {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> Signal<Self> {
        Signal::new(origin_route, self)
    }
}
#[rustfmt::skip]
impl signal::Signal<Input> {
    pub fn message_sent(&self, identifier: MessageIdentifier) -> MessageSent {
        MessageSent {
            identifier,
            origin_route: self.origin_route(),
            root: MessageRoot::Input,
            short_header: self.root().short_header(),
        }
    }
}
#[rustfmt::skip]
impl Output {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> Signal<Self> {
        Signal::new(origin_route, self)
    }
}
#[rustfmt::skip]
impl signal::Signal<Output> {
    pub fn message_sent(&self, identifier: MessageIdentifier) -> MessageSent {
        MessageSent {
            identifier,
            origin_route: self.origin_route(),
            root: MessageRoot::Output,
            short_header: self.root().short_header(),
        }
    }
}

#[rustfmt::skip]
#[allow(clippy::module_inception)]
pub mod signal {
    pub type Input = super::Input;
    pub type Output = super::Output;
    pub type Signal<Root> = super::Signal<Root>;
}

#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum EngineStartFailure {
    ResourceBusy(String),
    ConfigurationInvalid(String),
}
#[rustfmt::skip]
impl std::fmt::Display for EngineStartFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceBusy(message) => {
                write!(formatter, "engine resource busy: {message}")
            }
            Self::ConfigurationInvalid(message) => {
                write!(formatter, "engine configuration invalid: {message}")
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for EngineStartFailure {}
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum EngineStopFailure {
    ResourceLocked(String),
    ChildStillRunning(String),
}
#[rustfmt::skip]
impl std::fmt::Display for EngineStopFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceLocked(message) => {
                write!(formatter, "engine resource locked: {message}")
            }
            Self::ChildStillRunning(message) => {
                write!(formatter, "engine child still running: {message}")
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for EngineStopFailure {}

#[rustfmt::skip]
pub trait SignalEngine: Send {
    type NexusInput;
    type NexusOutput;
    fn on_start(&mut self) -> Result<(), EngineStartFailure> {
        Ok(())
    }
    fn on_stop(&mut self) -> Result<(), EngineStopFailure> {
        Ok(())
    }
    fn trace_signal_activation(&self, _object_name: SignalObjectName) {}
    fn trace_signal_admitted(&self) {
        self.trace_signal_activation(SignalObjectName::Admitted);
    }
    fn trace_signal_rejected(&self) {
        self.trace_signal_activation(SignalObjectName::Rejected);
    }
    fn trace_signal_triaged(&self) {
        self.trace_signal_activation(SignalObjectName::Triaged);
    }
    fn trace_signal_replied(&self) {
        self.trace_signal_activation(SignalObjectName::Replied);
    }
    fn triage_inner(&self, input: signal::Signal<signal::Input>) -> Self::NexusInput;
    fn reply_inner(&self, output: Self::NexusOutput) -> signal::Signal<signal::Output>;
    fn triage(&self, input: signal::Signal<signal::Input>) -> Self::NexusInput {
        let output = self.triage_inner(input);
        self.trace_signal_triaged();
        output
    }
    fn reply(&self, output: Self::NexusOutput) -> signal::Signal<signal::Output> {
        let signal_output = self.reply_inner(output);
        self.trace_signal_replied();
        signal_output
    }
}

#[rustfmt::skip]
pub trait UpgradeFrom<Previous>: Sized {
    type Error;
    fn upgrade_from(previous: Previous) -> Result<Self, Self::Error>;
}
#[rustfmt::skip]
pub trait AcceptPrevious<Previous>: UpgradeFrom<Previous> {
    fn accept_previous(previous: Previous) -> Result<Self, Self::Error> {
        Self::upgrade_from(previous)
    }
}
#[rustfmt::skip]
impl<Current, Previous> AcceptPrevious<Previous> for Current
where
    Current: UpgradeFrom<Previous>,
{}
